// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#ifndef ITKPROCESSREGISTRATIONDIFFEOMORPHICDEMONSPLUGINEXPORT_H
#define ITKPROCESSREGISTRATIONDIFFEOMORPHICDEMONSPLUGINEXPORT_H

#ifdef WIN32
    #ifdef itkProcessRegistrationDiffeomorphicDemonsPlugin_EXPORTS
        #define ITKPROCESSREGISTRATIONDIFFEOMORPHICDEMONSPLUGIN_EXPORT __declspec(dllexport) 
    #else
        #define ITKPROCESSREGISTRATIONDIFFEOMORPHICDEMONSPLUGIN_EXPORT __declspec(dllimport) 
    #endif
#else
    #define ITKPROCESSREGISTRATIONDIFFEOMORPHICDEMONSPLUGIN_EXPORT
#endif

#endif
