// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#include "itkProcessRegistrationDiffeoMorphicDemons.h"
#include "itkProcessRegistrationDiffeoMorphicDemonsPlugin.h"
#include "itkProcessRegistrationDiffeoMorphicDemonsToolBox.h"

#include <dtkCore/dtkLog.h>

// /////////////////////////////////////////////////////////////////
// itkProcessRegistrationDiffeoMorphicDemonsPluginPrivate
// /////////////////////////////////////////////////////////////////

class itkProcessRegistrationDiffeoMorphicDemonsPluginPrivate
{
public:
    // Class variables go here.
};

// /////////////////////////////////////////////////////////////////
// itkProcessRegistrationDiffeoMorphicDemonsPlugin
// /////////////////////////////////////////////////////////////////

itkProcessRegistrationDiffeoMorphicDemonsPlugin::itkProcessRegistrationDiffeoMorphicDemonsPlugin(QObject *parent) : dtkPlugin(parent), d(new itkProcessRegistrationDiffeoMorphicDemonsPluginPrivate)
{

}

itkProcessRegistrationDiffeoMorphicDemonsPlugin::~itkProcessRegistrationDiffeoMorphicDemonsPlugin(void)
{
    delete d;

    d = NULL;
}

bool itkProcessRegistrationDiffeoMorphicDemonsPlugin::initialize(void)
{
    if(!itkProcessRegistrationDiffeoMorphicDemons::registered())
        dtkWarning() << "Unable to register itkProcessRegistrationDiffeoMorphicDemons type";

    if(!itkProcessRegistrationDiffeoMorphicDemonsToolBox::registered())
        dtkWarning() << "Unable to register itkProcessRegistrationDiffeoMorphicDemons toolbox";

    return true;
}

bool itkProcessRegistrationDiffeoMorphicDemonsPlugin::uninitialize(void)
{
    return true;
}

QString itkProcessRegistrationDiffeoMorphicDemonsPlugin::name(void) const
{
    return "itkProcessRegistrationDiffeoMorphicDemonsPlugin";
}

QString itkProcessRegistrationDiffeoMorphicDemonsPlugin::description(void) const
{
    return "";
}

QStringList itkProcessRegistrationDiffeoMorphicDemonsPlugin::tags(void) const
{
    return QStringList();
}

QStringList itkProcessRegistrationDiffeoMorphicDemonsPlugin::types(void) const
{
    return QStringList() << "itkProcessRegistrationDiffeoMorphicDemons";
}

Q_EXPORT_PLUGIN2(itkProcessRegistrationDiffeoMorphicDemonsPlugin, itkProcessRegistrationDiffeoMorphicDemonsPlugin)
