// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#include "itkProcessRegistrationDiffeomorphicDemons.h"
#include "itkProcessRegistrationDiffeomorphicDemonsPlugin.h"
#include "itkProcessRegistrationDiffeomorphicDemonsToolBox.h"
#include "itkProcessRegistrationDiffeomorphicDemonsDefinitions.h"

#include <dtkCore/dtkLog.h>

// /////////////////////////////////////////////////////////////////
// itkProcessRegistrationDiffeomorphicDemonsPluginPrivate
// /////////////////////////////////////////////////////////////////

class itkProcessRegistrationDiffeomorphicDemonsPluginPrivate
{
public:
    // Class variables go here.
};

// /////////////////////////////////////////////////////////////////
// itkProcessRegistrationDiffeomorphicDemonsPlugin
// /////////////////////////////////////////////////////////////////

itkProcessRegistrationDiffeomorphicDemonsPlugin::itkProcessRegistrationDiffeomorphicDemonsPlugin(QObject *parent) : dtkPlugin(parent), d(new itkProcessRegistrationDiffeomorphicDemonsPluginPrivate)
{

}

itkProcessRegistrationDiffeomorphicDemonsPlugin::~itkProcessRegistrationDiffeomorphicDemonsPlugin(void)
{
    delete d;

    d = NULL;
}

bool itkProcessRegistrationDiffeomorphicDemonsPlugin::initialize(void)
{
    if(!itkProcessRegistrationDiffeomorphicDemons::registered())
        dtkWarning() << "Unable to register itkProcessRegistrationDiffeomorphicDemons type";

    if(!itkProcessRegistrationDiffeomorphicDemonsToolBox::registered())
        dtkWarning() << "Unable to register itkProcessRegistrationDiffeomorphicDemons toolbox";

    return true;
}

bool itkProcessRegistrationDiffeomorphicDemonsPlugin::uninitialize(void)
{
    return true;
}

QString itkProcessRegistrationDiffeomorphicDemonsPlugin::name(void) const
{
    return "itkProcessRegistrationDiffeomorphicDemonsPlugin";
}

QString itkProcessRegistrationDiffeomorphicDemonsPlugin::contact(void) const
{
    return QString::fromUtf8("Benoît Bleuzé benoit.bleuze@inria.fr");
}

QString itkProcessRegistrationDiffeomorphicDemonsPlugin::description(void) const
{
    return "Applies the diffeomorphic demons as they can be found in itk. Converts any type of image to float before applying the change, since the diffeomorphic demons only work on float images <br/> see: <a href=\"http://www.insight-journal.org/browse/publication/154\" > http://www.insight-journal.org/browse/publication/154 </a>";
}


QString itkProcessRegistrationDiffeomorphicDemonsPlugin::version(void) const
{
    return PLUGIN_VERSION;
}



QStringList itkProcessRegistrationDiffeomorphicDemonsPlugin::tags(void) const
{
    return QStringList();
}


QStringList itkProcessRegistrationDiffeomorphicDemonsPlugin::types(void) const
{
    return QStringList() << "itkProcessRegistrationDiffeomorphicDemons";
}

Q_EXPORT_PLUGIN2(itkProcessRegistrationDiffeomorphicDemonsPlugin, itkProcessRegistrationDiffeomorphicDemonsPlugin)
