// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#include "medViewSegmentation.h"

#include <dtkCore/dtkAbstractViewFactory.h>

#include "medSegmentationConfiguration.h"

// /////////////////////////////////////////////////////////////////
// medViewSegmentationPrivate
// /////////////////////////////////////////////////////////////////

class medViewSegmentationPrivate
{
public:
};

// /////////////////////////////////////////////////////////////////
// medViewSegmentation
// /////////////////////////////////////////////////////////////////

medViewSegmentation::medViewSegmentation(void) : dtkAbstractView(), d(new medViewSegmentationPrivate)
{

}

medViewSegmentation::~medViewSegmentation(void)
{
    delete d;
    d = NULL;
}

bool medViewSegmentation::registered(void)
{
    return dtkAbstractViewFactory::instance()->registerViewType("medViewSegmentation", medViewSegmentation::createMedViewSegmentation);
}

QString medViewSegmentation::description(void) const
{
    return "medViewSegmentation";
}

// /////////////////////////////////////////////////////////////////
// Type instantiation
// /////////////////////////////////////////////////////////////////
//static
dtkAbstractView *medViewSegmentation::createMedViewSegmentation(void)
{
    return new medViewSegmentation;
}
