// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#ifndef MEDVIEWSEGMENTATION_H
#define MEDVIEWSEGMENTATION_H

#include <dtkCore/dtkAbstractView.h>

#include "medViewSegmentationPluginExport.h"

class medViewSegmentationPrivate;

class MEDVIEWSEGMENTATIONPLUGIN_EXPORT medViewSegmentation : public dtkAbstractView
{
    Q_OBJECT

public:
             medViewSegmentation(void);
    virtual ~medViewSegmentation(void);

    virtual QString description(void) const;

    static bool registered(void);

    static dtkAbstractView *createMedViewSegmentation(void);

private:
    medViewSegmentationPrivate *d;
};

#endif
