// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#ifndef MEDVIEWSEGMENTATION_H
#define MEDVIEWSEGMENTATION_H

#include <dtkCore/dtkAbstractView.h>

#include "msegPluginExport.h"

//Forward declarations
namespace mseg {
    class Controller;
}

class medAbstractView;
class medAbstractViewScene;

namespace mseg {

class MEDVIEWSEGMENTATIONPLUGIN_EXPORT View : public dtkAbstractView
{
    Q_OBJECT

public:
             View( Controller * controller);
    virtual ~View(void);

    virtual QString description(void) const;

    void installOnView(medAbstractView * view);
    void removeFromView(medAbstractView * view);
    void removeFromAllViews();

protected:
    bool eventFilter(QObject *obj, QEvent *event);

    medAbstractViewScene * scene(medAbstractView * view);

    virtual bool mousePressEvent( medAbstractViewScene *vscene, QGraphicsSceneMouseEvent *mouseEvent );
    virtual bool mouseReleaseEvent( medAbstractViewScene *vscene, QGraphicsSceneMouseEvent *mouseEvent );
    virtual bool mouseMoveEvent( medAbstractViewScene *vscene, QGraphicsSceneMouseEvent *mouseEvent );

private:
    static QString s_description();

    Controller * m_segmentationController;
    QSet<medAbstractView *> m_views;

};

} // namespace mseg

#endif
