/*=========================================================================

 medInria

 Copyright (c) INRIA 2013 All rights reserved.
 See LICENSE.txt for details in the root of the sources or:
 https://github.com/medInria/medInria-public/blob/master/LICENSE.txt

 This software is distributed WITHOUT ANY WARRANTY; without even
  the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
  PURPOSE.

=========================================================================*/

// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#pragma once

#include <itkDataImageReaderBase.h>
#include "itkINRDataImageReaderPluginExport.h"

class itkINRDataImageReaderPrivate;

class ITKINRDATAIMAGEREADERPLUGIN_EXPORT itkINRDataImageReader : public itkDataImageReaderBase
{
public:
             itkINRDataImageReader(void);
    virtual ~itkINRDataImageReader(void);

    virtual QString identifier()  const;
    virtual QString description(void) const;

    QStringList handled() const;

    static QStringList s_handled();

    static bool registered(void);

private:
    itkINRDataImageReaderPrivate *d;
    static const char ID[];
};

dtkAbstractDataReader *createItkINRDataImageReader(void);
