// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#ifndef %2PLUGINEXPORT_H
#define %2PLUGINEXPORT_H

#ifdef WIN32
    #ifdef %1Plugin_EXPORTS
        #define %2PLUGIN_EXPORT __declspec(dllexport) 
    #else
        #define %2PLUGIN_EXPORT __declspec(dllimport) 
    #endif
#else
    #define %2PLUGIN_EXPORT
#endif

#endif
