// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#pragma once

#ifdef WIN32
    #ifdef itkDataImagePlugin_EXPORTS
        #define ITKDATAIMAGEPLUGIN_EXPORT __declspec(dllexport) 
    #else
        #define ITKDATAIMAGEPLUGIN_EXPORT __declspec(dllimport) 
    #endif
#else
    #define ITKDATAIMAGEPLUGIN_EXPORT
#endif



