// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#ifndef MEDDATABASEPACSPLUGIN_H
#define MEDDATABASEPACSPLUGIN_H

#include <dtkCore/dtkPlugin.h>

#include "medDatabasePacsPluginExport.h"

class MEDDATABASEPACSPLUGIN_EXPORTS medDatabasePacsPluginPrivate;

class MEDDATABASEPACSPLUGIN_EXPORTS medDatabasePacsPlugin : public dtkPlugin
{
    Q_OBJECT
    Q_INTERFACES(dtkPlugin)

public:
     medDatabasePacsPlugin(QObject *parent = 0);
    ~medDatabasePacsPlugin(void);

    virtual bool initialize(void);
    virtual bool uninitialize(void);

    virtual QString name(void) const;
    virtual QString description(void) const;

    virtual QStringList tags(void) const;
    virtual QStringList types(void) const;

private:
     medDatabasePacsPluginPrivate *d;
};

#endif
