// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#ifndef ITKDATASHIMAGEWRITERPLUGIN_H
#define ITKDATASHIMAGEWRITERPLUGIN_H

#include <dtkCore/dtkPlugin.h>

#include "itkDataShImageWriterPluginExport.h"

class ITKDATASHIMAGEWRITERPLUGIN_EXPORT itkDataShImageWriterPluginPrivate;

class ITKDATASHIMAGEWRITERPLUGIN_EXPORT itkDataShImageWriterPlugin : public dtkPlugin
{
    Q_OBJECT
    Q_INTERFACES(dtkPlugin)

public:
     itkDataShImageWriterPlugin(QObject *parent = 0);
    ~itkDataShImageWriterPlugin(void);

    virtual bool initialize(void);
    virtual bool uninitialize(void);

    virtual QString name(void) const;
    virtual QString description(void) const;

    virtual QStringList tags(void) const;
    virtual QStringList types(void) const;

private:
     itkDataShImageWriterPluginPrivate *d;
};

#endif
