#!/bin/sh
#
# @WARNING_MESSAGE@
# If you just want to add another hook, add it to
# utils/git/medInria-hooks.sh

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

$PWD/utils/git/medInria-hooks.sh $against

exec git diff-index --check --cached $against --
