// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#include <vtkINRIA3DConfigure.h>

#ifdef vtkINRIA3D_USE_ITK
#include "medItk/medItk.h"
#include "itkExtractImageFilter.h"
#endif

#include "v3dView.h"

#include <dtkCore/dtkAbstractViewFactory.h>
#include <dtkCore/dtkAbstractDataImage.h>

#include <vtkCamera.h>
#include <vtkCommand.h>
#include <vtkRenderer.h>
#include <vtkRenderWindow.h>
#include <vtkLookupTableManager.h>
#include <vtkImageActor.h>
#include <vtkImageData.h>
#include <vtkPointSet.h>
#include <vtkTextProperty.h>

#include <vtkImageView2D.h>
#include <vtkImageView3D.h>
#include <vtkInteractorStyleImageView2D.h>
#include <vtkInteractorStyleTrackballCamera2.h>
#include <vtkImageViewCollection.h>

#include <QVTKWidget.h>

#include <QtGui>
#include <QMenu>
#include <QMouseEvent>

// /////////////////////////////////////////////////////////////////////////////////////////////////////////
// v3dViewObserver: links a QSlider with the CurrentPointChangedEvent of a vtkImageView instance.
// /////////////////////////////////////////////////////////////////////////////////////////////////////////

class v3dViewObserver : public vtkCommand
{
public:
    static v3dViewObserver* New(void) { return new v3dViewObserver; }

    void Execute(vtkObject *caller, unsigned long event, void *callData);

    void SetSlider(QSlider *slider) {
        this->slider = slider;
    }

    inline void   Lock(void) { this->lock = 1; }
    inline void UnLock(void) { this->lock = 0; }

protected:
     v3dViewObserver(void);
    ~v3dViewObserver(void);

private:
    int lock;
    QSlider *slider;
};

v3dViewObserver::v3dViewObserver(void)
{
    this->slider = 0;
    this->lock = 0;
}

v3dViewObserver::~v3dViewObserver(void)
{

}

void v3dViewObserver::Execute(vtkObject *caller, unsigned long event, void *callData)
{
    vtkImageView2D* view = vtkImageView2D::SafeDownCast (caller);

    if(!view )
        return;

    if(event == vtkImageView::CurrentPointChangedEvent && !this->lock) {
        if(this->slider ) {
            unsigned int zslice = view->GetSlice();
            this->slider->blockSignals (true);
            this->slider->setValue (zslice);
	    this->slider->update();
            this->slider->blockSignals (false);
        }
    }
}

// /////////////////////////////////////////////////////////////////
// v3dViewPrivate
// /////////////////////////////////////////////////////////////////

class v3dViewPrivate
{
public:
    vtkRenderer *renderer2DAxial;
    vtkRenderer *renderer2DSagittal;
    vtkRenderer *renderer2DCoronal;
    vtkRenderer *renderer3D;
    vtkImageView2D *view2DAxial;
    vtkImageView2D *view2DSagittal;
    vtkImageView2D *view2DCoronal;
    vtkImageView3D *view3D;

    vtkImageView *currentView;
  
    vtkImageViewCollection *collection;
    v3dViewObserver *observer;

    QWidget *widget;
    QSlider *slider;
    QVTKWidget *vtkWidget;
    QMenu *menu;
    QString orientation;

    dtkAbstractData *data;
};

// /////////////////////////////////////////////////////////////////
// v3dView
// /////////////////////////////////////////////////////////////////

v3dView::v3dView(void) : dtkAbstractView(), d(new v3dViewPrivate)
{
    d->data = 0;
    d->orientation = "Axial";

    // Setting up 2D view
    
    d->renderer2DAxial = vtkRenderer::New();
    d->view2DAxial = vtkImageView2D::New();    
    d->view2DAxial->SetRenderer(d->renderer2DAxial);
    d->view2DAxial->SetBackground(0.0, 0.0, 0.0);
    d->view2DAxial->SetLeftButtonInteractionStyle(vtkInteractorStyleImageView2D::InteractionTypeZoom);
    d->view2DAxial->SetMiddleButtonInteractionStyle(vtkInteractorStyleImageView2D::InteractionTypeSlice);
    d->view2DAxial->SetRightButtonInteractionStyle(vtkInteractorStyleImageView2D::InteractionTypeNull);
    d->view2DAxial->SetSliceOrientation(vtkImageView2D::VIEW_ORIENTATION_AXIAL);
    d->view2DAxial->CursorFollowMouseOn();
    d->view2DAxial->ShowImageAxisOff();
    d->view2DAxial->ShowScalarBarOff();
    d->view2DAxial->ShowRulerWidgetOn();
    
    d->renderer2DSagittal = vtkRenderer::New();
    d->view2DSagittal = vtkImageView2D::New();    
    d->view2DSagittal->SetRenderer(d->renderer2DSagittal);
    d->view2DSagittal->SetBackground(0.0, 0.0, 0.0);
    d->view2DSagittal->SetLeftButtonInteractionStyle(vtkInteractorStyleImageView2D::InteractionTypeZoom);
    d->view2DSagittal->SetMiddleButtonInteractionStyle(vtkInteractorStyleImageView2D::InteractionTypeSlice);
    d->view2DSagittal->SetRightButtonInteractionStyle(vtkInteractorStyleImageView2D::InteractionTypeNull);
    d->view2DSagittal->SetSliceOrientation(vtkImageView2D::VIEW_ORIENTATION_SAGITTAL);
    d->view2DSagittal->CursorFollowMouseOn();
    d->view2DSagittal->ShowImageAxisOff();
    d->view2DSagittal->ShowScalarBarOff();
    d->view2DSagittal->ShowRulerWidgetOn();

    d->renderer2DCoronal = vtkRenderer::New();
    d->view2DCoronal = vtkImageView2D::New();    
    d->view2DCoronal->SetRenderer(d->renderer2DCoronal);
    d->view2DCoronal->SetBackground(0.0, 0.0, 0.0);
    d->view2DCoronal->SetLeftButtonInteractionStyle(vtkInteractorStyleImageView2D::InteractionTypeZoom);
    d->view2DCoronal->SetMiddleButtonInteractionStyle(vtkInteractorStyleImageView2D::InteractionTypeSlice);
    d->view2DCoronal->SetRightButtonInteractionStyle(vtkInteractorStyleImageView2D::InteractionTypeNull);
    d->view2DCoronal->SetSliceOrientation(vtkImageView2D::VIEW_ORIENTATION_CORONAL);
    d->view2DCoronal->CursorFollowMouseOn();
    d->view2DCoronal->ShowImageAxisOff();
    d->view2DCoronal->ShowScalarBarOff();
    d->view2DCoronal->ShowRulerWidgetOn();
    
    d->currentView = d->view2DAxial;

    // Setting up 3D view
    d->renderer3D = vtkRenderer::New();
    d->view3D = vtkImageView3D::New();
    d->view3D->SetRenderer(d->renderer3D);
    d->view3D->SetShowBoxWidget(0);
    d->view3D->SetCroppingModeToOff();
    d->view3D->ShowScalarBarOff();
	d->view3D->GetTextProperty()->SetColor(1.0, 1.0, 1.0);
    d->view3D->ShadeOn();

    vtkInteractorStyleTrackballCamera2 *interactorStyle = vtkInteractorStyleTrackballCamera2::New();
    d->view3D->SetInteractorStyle(interactorStyle);
    interactorStyle->Delete();

    d->widget = new QWidget;

    d->slider = new QSlider(Qt::Horizontal, d->widget);
    d->slider->setSizePolicy(QSizePolicy::Minimum, QSizePolicy::Fixed);
    d->slider->setFocusPolicy(Qt::NoFocus);

    d->vtkWidget = new QVTKWidget(d->widget);
    d->vtkWidget->setSizePolicy(QSizePolicy::Minimum, QSizePolicy::Minimum);
    d->vtkWidget->setFocusPolicy(Qt::NoFocus);

    vtkRenderWindow* renwin = vtkRenderWindow::New();
    renwin->StereoCapableWindowOn();
    renwin->SetStereoTypeToCrystalEyes();
    // if(qApp->arguments().contains("--stereo"))
    //     renwin->SetStereoRender(1);
    d->vtkWidget->SetRenderWindow(renwin);

    QVBoxLayout *layout = new QVBoxLayout(d->widget);
    layout->setContentsMargins(0, 0, 0, 0);
    layout->setSpacing(0);
    layout->addWidget(d->slider);
    layout->addWidget(d->vtkWidget);

    //d->view3D->SetRenderWindow(d->vtkWidget->GetRenderWindow());
    d->view3D->SetRenderWindowInteractor(d->vtkWidget->GetRenderWindow()->GetInteractor());
    d->view3D->UnInstallInteractor();
    d->vtkWidget->GetRenderWindow()->RemoveRenderer(d->renderer3D);
    
    //d->view2DCoronal->SetRenderWindow(d->vtkWidget->GetRenderWindow());
    d->view2DCoronal->SetRenderWindowInteractor(d->vtkWidget->GetRenderWindow()->GetInteractor());
    d->vtkWidget->GetRenderWindow()->RemoveRenderer(d->renderer2DCoronal);
    d->view2DCoronal->UnInstallInteractor();

    //d->view2DSagittal->SetRenderWindow(d->vtkWidget->GetRenderWindow());
    d->view2DSagittal->SetRenderWindowInteractor(d->vtkWidget->GetRenderWindow()->GetInteractor());
    d->vtkWidget->GetRenderWindow()->RemoveRenderer(d->renderer2DSagittal);
    d->view2DSagittal->UnInstallInteractor();

    d->view2DAxial->SetRenderWindow(d->vtkWidget->GetRenderWindow()); // set the interactor as well
    //d->view2DAxial->SetRenderWindowInteractor(d->vtkWidget->GetRenderWindow()->GetInteractor());

    d->collection = vtkImageViewCollection::New();
    d->collection->AddItem (d->view2DAxial);
    d->collection->AddItem (d->view2DCoronal);
    d->collection->AddItem (d->view2DSagittal);
    d->collection->AddItem (d->view3D);

    d->collection->SetLinkCurrentPoint (0);
    d->collection->SetLinkSliceMove (0);
    d->collection->SetLinkColorWindowLevel (0);
    d->collection->SetLinkCamera (0);
    d->collection->SetLinkZoom (0);
    d->collection->SetLinkRequestedPosition (0);

    d->observer = v3dViewObserver::New();
    d->observer->SetSlider(d->slider);
    d->view2DAxial->AddObserver(vtkImageView::CurrentPointChangedEvent, d->observer, 5);

    QAction *axialAct = new QAction(tr("Axial"), d->vtkWidget);
    connect(axialAct, SIGNAL(triggered()), this, SLOT(onMenuAxialTriggered()));

    QAction *coronalAct = new QAction(tr("Coronal"), d->vtkWidget);
    connect(coronalAct, SIGNAL(triggered()), this, SLOT(onMenuCoronalTriggered()));

    QAction *sagittalAct = new QAction(tr("Sagittal"), d->vtkWidget);
    connect(sagittalAct, SIGNAL(triggered()), this, SLOT(onMenuSagittalTriggered()));

    QAction *vrAct = new QAction(tr("VR"), d->vtkWidget);
    connect(vrAct, SIGNAL(triggered()), this, SLOT(onMenu3DVRTriggered()));

    QAction *maxipAct = new QAction(tr("MIP - Max"), d->vtkWidget);
    connect(maxipAct, SIGNAL(triggered()), this, SLOT(onMenu3DMaxIPTriggered()));

    QAction *minipAct = new QAction(tr("MIP - Min"), d->vtkWidget);
    connect(minipAct, SIGNAL(triggered()), this, SLOT(onMenu3DMinIPTriggered()));
    
    QAction *mprAct = new QAction(tr("MPR"), d->vtkWidget);
    connect(mprAct, SIGNAL(triggered()), this, SLOT(onMenu3DMPRTriggered()));
    
    QAction *zoomAct = new QAction(tr("Zoom"), d->vtkWidget);
    connect(zoomAct, SIGNAL(triggered()), this, SLOT(onMenuZoomTriggered()));

    QAction *wlAct = new QAction(tr("Window / Level"), d->vtkWidget);
    connect(wlAct, SIGNAL(triggered()), this, SLOT(onMenuWindowLevelTriggered()));

    QActionGroup *group = new QActionGroup(d->vtkWidget);
    group->addAction(zoomAct);
    group->addAction(wlAct);
    wlAct->setChecked(true);
    
    d->menu = new QMenu(d->vtkWidget );
    d->menu->addAction(axialAct);
    d->menu->addAction(coronalAct);
    d->menu->addAction(sagittalAct);

    QMenu *tridMenu = d->menu->addMenu (tr ("3D"));
    tridMenu->addAction (vrAct);
    tridMenu->addAction (maxipAct);
    tridMenu->addAction (minipAct);
    tridMenu->addAction (mprAct);

    d->menu->addSeparator();
    d->menu->addAction(zoomAct);
    d->menu->addAction(wlAct);

    QStringList lut;
    lut << "Default"
	<< "Black&White"
	<< "Black&WhiteInversed"
	<< "Spectrum"
	<< "HotMetal"
	<< "GE"
	<< "Flow"
	<< "Loni"
	<< "Loni2"
	<< "Asymmetry"
	<< "PValue"
	<< "blueBlackAlpha"
	<< "greenBlackAlpha"
	<< "redBlackAlpha"
	<< "Muscles&Bones"
      	<< "Red Vessels"
      	<< "Bones"
	<< "Stern";
    
    
    this->addProperty ("Orientation",           QStringList() << "Axial" << "Sagittal" << "Coronal" << "3D");
    this->addProperty ("ScalarBarVisibility",   QStringList() << "true" << "false");
    this->addProperty ("LookupTable",           lut);
    this->addProperty ("BackgroundLookupTable", lut);
    this->addProperty ("Opacity",               QStringList() << "1.0");
    this->addProperty ("ShowAxis",              QStringList() << "true" << "false");
    this->addProperty ("LeftClickInteraction",  QStringList() << "Zooming" << "Windowing" << "Slicing" << "Measuring");
    this->addProperty ("Mode",                  QStringList() << "VR" << "MPR" << "MIP - Maximum" << "MIP - Minimum");
    this->addProperty ("Cropping",              QStringList() << "true" << "false");
    this->addProperty ("Preset",                QStringList() << "None" << "VR Muscles&Bones"
		                                              << "Vascular I" << "Vascular II" << "Vascular III" << "Vascular IV"
		                                              << "Standard" << "Soft" << "Soft on White" << "Soft on Blue"
		                                              << "Red on White" << "Glossy");

    // set default properties
    this->setProperty ("Orientation", "Axial");
    this->setProperty ("ScalarBarVisibility", "false");
    this->setProperty ("ShowAxis", "false");
    this->setProperty ("LookupTable", "Default");
    this->setProperty ("BackgroundLookupTable", "Default");
    this->setProperty ("Opacity", "1.0");
    this->setProperty ("LeftClickInteraction", "Zooming");
    this->setProperty ("Mode", "VR");
    this->setProperty ("Preset", "None");

    connect(d->vtkWidget, SIGNAL(mouseEvent(QMouseEvent*)), this, SLOT(onMousePressEvent(QMouseEvent*)));
    connect(d->slider,    SIGNAL(valueChanged(int)),        this, SLOT(onZSliderValueChanged(int)));
}

v3dView::~v3dView(void)
{
    d->vtkWidget->GetRenderWindow()->RemoveRenderer(d->renderer2DAxial);
    d->vtkWidget->GetRenderWindow()->RemoveRenderer(d->renderer2DCoronal);
    d->vtkWidget->GetRenderWindow()->RemoveRenderer(d->renderer2DSagittal);
    d->vtkWidget->GetRenderWindow()->RemoveRenderer(d->renderer3D);

    /*
      d->view2D->SetRenderWindow(0);
      d->view2D->SetRenderWindowInteractor(0);
      d->view3D->SetRenderWindow(0);
      d->view3D->SetRenderWindowInteractor(0);
    */

    d->view2DAxial->Delete();
    d->view2DSagittal->Delete();
    d->view2DCoronal->Delete();
    d->renderer2DAxial->Delete();
    d->renderer2DSagittal->Delete();
    d->renderer2DCoronal->Delete();
    d->view3D->UnInstallInteractor();
    d->view3D->Delete();
    d->renderer3D->Delete();
    d->observer->Delete();

    delete d;

    d = NULL;
}

bool v3dView::registered(void)
{
    return dtkAbstractViewFactory::instance()->registerViewType("v3dView", createV3dView);
}

QString v3dView::description(void) const
{
    return "v3dView";
}

// /////////////////////////////////////////////////////////////////
// 
// /////////////////////////////////////////////////////////////////

void v3dView::clear(void)
{
    d->collection->SyncSetInput (0); // to be tested
}

void v3dView::reset(void)
{
    if(!d->collection)
	return;
    
    d->collection->SyncReset();
}

void v3dView::update(void)
{
    if( d->currentView )
        d->currentView->Render();
    d->vtkWidget->update();
}

void v3dView::link(dtkAbstractView *other)
{
    if(!d->collection)
        return;

    if(!other)
        return;

    if(vtkImageView *view = dynamic_cast<vtkImageView*>((vtkObject*)(other->view()))) {
        d->collection->AddItem (view);
    }
}

void v3dView::unlink(dtkAbstractView *other)
{
    Q_UNUSED(other);
}

void *v3dView::view(void)
{
    return d->currentView;
}

vtkImageView *v3dView::viewAxial(void)
{
	return d->view2DAxial;
}

vtkImageView *v3dView::viewCoronal(void)
{
	return d->view2DCoronal;
}

vtkImageView *v3dView::viewSagittal(void)
{
	return d->view2DSagittal;
}

vtkImageView *v3dView::view3D(void)
{
	return d->view3D;
}

vtkRenderWindowInteractor *v3dView::interactor(void)
{
	return d->vtkWidget->GetRenderWindow()->GetInteractor();
}

vtkRenderer *v3dView::rendererAxial(void)
{
	return d->renderer2DAxial;
}

vtkRenderer *v3dView::rendererSagittal(void)
{
	return d->renderer2DSagittal;
}

vtkRenderer *v3dView::rendererCoronal(void)
{
	return d->renderer2DCoronal;
}

vtkRenderer *v3dView::renderer3D(void)
{
	return d->renderer3D;
}

void v3dView::setData(dtkAbstractData *data)
{
    if(!data)
        return;

    d->data = data;

    if (data->hasMetaData("PatientName")){
        const QString patientName = data->metaDataValues(tr("PatientName"))[0];	
        d->view2DAxial->SetPatientName (patientName.toAscii().constData());
	d->view2DSagittal->SetPatientName (patientName.toAscii().constData());
	d->view2DCoronal->SetPatientName (patientName.toAscii().constData());
        d->view3D->SetPatientName (patientName.toAscii().constData());
    }
    
    if( data->hasMetaData("StudyDescription")){
        const QString studyName = data->metaDataValues(tr("StudyDescription"))[0];
        d->view2DAxial->SetStudyName (studyName.toAscii().constData());
	d->view2DSagittal->SetStudyName (studyName.toAscii().constData());
	d->view2DCoronal->SetStudyName (studyName.toAscii().constData());
        d->view3D->SetStudyName (studyName.toAscii().constData());
    }
    
    if (data->hasMetaData("SeriesDescription")){
        const QString seriesName = data->metaDataValues(tr("SeriesDescription"))[0];
        d->view2DAxial->SetSeriesName (seriesName.toAscii().constData());
	d->view2DSagittal->SetSeriesName (seriesName.toAscii().constData());
	d->view2DCoronal->SetSeriesName (seriesName.toAscii().constData());
        d->view3D->SetSeriesName (seriesName.toAscii().constData());
    }

#ifdef vtkINRIA3D_USE_ITK
    if( itk::Image<char, 3>* image = dynamic_cast<itk::Image<char, 3>*>( (itk::Object*)( data->data() ) ) ) {
        d->view2DAxial->SetITKInput(image);
	d->view2DSagittal->SetITKInput(image);
	d->view2DCoronal->SetITKInput(image);
        d->view3D->SetITKInput(image);
    }
    else if( itk::Image<unsigned char, 3>* image = dynamic_cast<itk::Image<unsigned char, 3>*>( (itk::Object*)( data->data() ) ) ) {
        d->view2DAxial->SetITKInput(image);
	d->view2DSagittal->SetITKInput(image);
	d->view2DCoronal->SetITKInput(image);
        d->view3D->SetITKInput(image);
    }
    else if( itk::Image<short, 3>* image = dynamic_cast<itk::Image<short, 3>*>( (itk::Object*)( data->data() ) ) ) {
        d->view2DAxial->SetITKInput(image);
	d->view2DSagittal->SetITKInput(image);
	d->view2DCoronal->SetITKInput(image);
        d->view3D->SetITKInput(image);
    }
    else if( itk::Image<short, 4>* image = dynamic_cast<itk::Image<short, 4>*>( (itk::Object*)( data->data() ) ) ) {
        itk::ExtractImageFilter< itk::Image<short, 4>, itk::Image<short, 3> >::Pointer extractor = itk::ExtractImageFilter< itk::Image<short, 4>, itk::Image<short, 3> >::New();
	itk::Image<short, 4>::SizeType size = image->GetLargestPossibleRegion().GetSize();
	itk::Image<short, 4>::IndexType index = {{0,0,0,0}};
	size[3] = 0;
	itk::Image<short, 4>::RegionType region;
	region.SetSize (size);
	region.SetIndex (index);

	extractor->SetExtractionRegion (region);
	extractor->SetInput ( image );
	try
	{
	  extractor->Update();
	}
	catch (itk::ExceptionObject &e) {
	  qDebug() << e.GetDescription();
	  return;
	}
        d->view2DAxial->SetITKInput( extractor->GetOutput() );
	d->view2DSagittal->SetITKInput( extractor->GetOutput() );
	d->view2DCoronal->SetITKInput( extractor->GetOutput() );
        d->view3D->SetITKInput( extractor->GetOutput() );
    }
    else if( itk::Image<unsigned short, 3>* image = dynamic_cast<itk::Image<unsigned short, 3>*>( (itk::Object*)( data->data() ) ) ) {
        d->view2DAxial->SetITKInput(image);
	d->view2DSagittal->SetITKInput(image);
	d->view2DCoronal->SetITKInput(image);
        d->view3D->SetITKInput(image);
    }
    else if( itk::Image<int, 3>* image = dynamic_cast<itk::Image<int, 3>*>( (itk::Object*)( data->data() ) ) ) {
        d->view2DAxial->SetITKInput(image);
	d->view2DSagittal->SetITKInput(image);
	d->view2DCoronal->SetITKInput(image);
        d->view3D->SetITKInput(image);
    }
    else if( itk::Image<unsigned int, 3>* image = dynamic_cast<itk::Image<unsigned int, 3>*>( (itk::Object*)( data->data() ) ) ) {
        d->view2DAxial->SetITKInput(image);
	d->view2DSagittal->SetITKInput(image);
	d->view2DCoronal->SetITKInput(image);
        d->view3D->SetITKInput(image);
    }
    else if( itk::Image<long, 3>* image = dynamic_cast<itk::Image<long, 3>*>( (itk::Object*)( data->data() ) ) ) {
        d->view2DAxial->SetITKInput(image);
	d->view2DSagittal->SetITKInput(image);
	d->view2DCoronal->SetITKInput(image);
        d->view3D->SetITKInput(image);
    }
    else if( itk::Image<unsigned long, 3>* image = dynamic_cast<itk::Image<unsigned long, 3>*>( (itk::Object*)( data->data() ) ) ) {
        d->view2DAxial->SetITKInput(image);
	d->view2DSagittal->SetITKInput(image);
	d->view2DCoronal->SetITKInput(image);
	d->view3D->SetITKInput(image);
    }
    else if( itk::Image<float, 3>* image = dynamic_cast<itk::Image<float, 3>*>( (itk::Object*)( data->data() ) ) ) {
        d->view2DAxial->SetITKInput(image);
	d->view2DSagittal->SetITKInput(image);
	d->view2DCoronal->SetITKInput(image);
        d->view3D->SetITKInput(image);
    }
    else if( itk::Image<double, 3>* image = dynamic_cast<itk::Image<double, 3>*>( (itk::Object*)( data->data() ) ) ) {
        d->view2DAxial->SetITKInput(image);
	d->view2DSagittal->SetITKInput(image);
	d->view2DCoronal->SetITKInput(image);
        d->view3D->SetITKInput(image);
    }
    else if( itk::Image<itk::RGBPixel<unsigned char>, 3> *image = dynamic_cast<itk::Image<itk::RGBPixel<unsigned char>, 3>*>( (itk::Object*)( data->data() ) ) ) {
        d->view2DAxial->SetITKInput(image);
	d->view2DSagittal->SetITKInput(image);
	d->view2DCoronal->SetITKInput(image);
        d->view3D->SetITKInput(image);
    }
    else if( itk::Image<itk::Vector<unsigned char, 3>, 3> *image = dynamic_cast<itk::Image<itk::Vector<unsigned char, 3>, 3>*>( (itk::Object*)( data->data() ) ) ) {
        d->view2DAxial->SetITKInput(image);
	d->view2DSagittal->SetITKInput(image);
	d->view2DCoronal->SetITKInput(image);
        d->view3D->SetITKInput(image);
    }
    else {
        qDebug() << "Cannot cast data into compatible data structure";
    }
#endif


    if(vtkImageData *dataset = dynamic_cast<vtkImageData*>((vtkDataObject *)(data->data()))) {
        d->collection->SyncSetInput(dataset);
    }
    
    if(dtkAbstractDataImage* imData = dynamic_cast<dtkAbstractDataImage*>(data) ) {
        if( d->orientation=="Axial") {
            d->slider->setRange(0, imData->zDimension()-1);
        }
	else if( d->orientation=="Sagittal") {
            d->slider->setRange(0, imData->xDimension()-1);
        }
	else if( d->orientation=="Coronal") {
            d->slider->setRange(0, imData->yDimension()-1);
        }
    }

    dtkAbstractView::setData(data);

    this->update();
}

void *v3dView::data (void)
{
    if (d->data)
        return d->data->output();

    return NULL;
}

QWidget *v3dView::widget(void)
{
    return d->widget;
}

void v3dView::onPropertySet(QString key, QString value)
{
    if(key == "Orientation")
	this->onOrientationPropertySet(value);

    if(key == "ScalarBarVisibility")
	this->onScalarBarVisibilityPropertySet(value);

    if(key == "LookupTable")
	this->onLookupTablePropertySet(value);

    if(key == "BackgroundLookupTable")
	this->onBackgroundLookupTablePropertySet(value);

    if(key == "Opacity")
	this->onOpacityPropertySet(value);

    if(key == "ShowAxis")
	this->onShowAxisPropertySet(value);

    if(key == "LeftClickInteraction")
	this->onLeftClickInteractionPropertySet(value);

    if(key == "Mode")
	this->onModePropertySet(value);

    if(key == "Preset")
	this->onPresetPropertySet(value);

    if(key == "Cropping")
	this->onCroppingPropertySet(value);

    this->widget()->update();
}

void v3dView::onOrientationPropertySet(QString value)
{
    if (value==d->orientation)
         return;
    
    double pos[3], window = 0.0, level = 0.0;
    if( d->currentView ) {
        d->currentView->GetCurrentPoint (pos);
        window = d->currentView->GetColorWindow();
        level  = d->currentView->GetColorLevel();
	
	d->currentView->UnInstallInteractor();
	d->currentView->SetRenderWindow( 0 );
	d->currentView->RemoveObserver(d->observer);
	d->vtkWidget->GetRenderWindow()->RemoveRenderer(d->currentView->GetRenderer());
    }

    if (value=="3D") {
        d->orientation = "3D";
	d->currentView = d->view3D;	
    }
    
    if (value == "Axial") {
        d->orientation = "Axial";
	d->currentView = d->view2DAxial;
	
	if ( dtkAbstractDataImage* imData = dynamic_cast<dtkAbstractDataImage*>(d->data) )
	    d->slider->setRange (0, imData->zDimension()-1);
    }

    if (value == "Sagittal") {
        d->orientation = "Sagittal";
	d->currentView = d->view2DSagittal;
	
	if ( dtkAbstractDataImage* imData = dynamic_cast<dtkAbstractDataImage*>(d->data) )
            d->slider->setRange (0, imData->xDimension()-1);
    }

    if (value == "Coronal") {
        d->orientation = "Coronal";
	d->currentView = d->view2DCoronal;
	
	if ( dtkAbstractDataImage* imData = dynamic_cast<dtkAbstractDataImage*>(d->data) )
            d->slider->setRange (0, imData->yDimension()-1);
    }

    if (!d->currentView)
      return;

    d->currentView->SetRenderWindow ( d->vtkWidget->GetRenderWindow() );
    //d->currentView->InstallInteractor();
    d->currentView->AddObserver(vtkImageView::CurrentPointChangedEvent, d->observer, 5);

    d->currentView->SetCurrentPoint (pos);
    d->currentView->SetColorWindow (window);
    d->currentView->SetColorLevel (level);	

    // force a correct display of the 2D axis for planar views
    d->currentView->InvokeEvent (vtkImageView::CurrentPointChangedEvent, NULL);
}

void v3dView::onModePropertySet (QString value)
{
  if (value=="VR") {
      d->view3D->SetRenderingModeToVR();
      d->view3D->SetVolumeRayCastFunctionToComposite();
  }

  if (value=="MPR") {
      d->view3D->SetRenderingModeToPlanar();
  }

  if (value=="MIP - Maximum") {
      d->view3D->SetRenderingModeToVR();
      d->view3D->SetVolumeRayCastFunctionToMaximumIntensityProjection();
  }

  if (value=="MIP - Minimum") {
      d->view3D->SetRenderingModeToVR();
      d->view3D->SetVolumeRayCastFunctionToMinimumIntensityProjection();
  }
  
}

void v3dView::onScalarBarVisibilityPropertySet(QString value)
{
    if (value == "true") {
      d->collection->SyncSetShowScalarBar(true);
    }

    if (value == "false") {
      d->collection->SyncSetShowScalarBar(false);
    }
}

void v3dView::onLookupTablePropertySet(QString value)
{
    if (value == "Default") {
        d->collection->SyncSetLookupTable(vtkLookupTableManager::GetBWLookupTable());
    }

    if (value == "Black&White") {
	d->collection->SyncSetLookupTable(vtkLookupTableManager::GetBWLookupTable());
    }

    if (value == "Black&WhiteInversed") {
	d->collection->SyncSetLookupTable(vtkLookupTableManager::GetBWInverseLookupTable());
    }

    if (value == "Spectrum") {
	d->collection->SyncSetLookupTable(vtkLookupTableManager::GetSpectrumLookupTable());
    }

    if (value == "HotMetal") {
	d->collection->SyncSetLookupTable(vtkLookupTableManager::GetHotMetalLookupTable());
    }

    if (value == "GE") {
	d->collection->SyncSetLookupTable(vtkLookupTableManager::GetGEColorLookupTable());
    }

    if (value == "Loni") {
	d->collection->SyncSetLookupTable(vtkLookupTableManager::GetLONILookupTable());
    }

    if (value == "Loni2") {
	d->collection->SyncSetLookupTable(vtkLookupTableManager::GetLONI2LookupTable());
    }

    if (value == "Asymmetry") {
	d->collection->SyncSetLookupTable(vtkLookupTableManager::GetAsymmetryLookupTable());
    }

    if (value == "PValue") {
	d->collection->SyncSetLookupTable(vtkLookupTableManager::GetPValueLookupTable());
    }

    if (value == "blueBlackAlpha") {
	d->collection->SyncSetLookupTable(vtkLookupTableManager::GetBlueBlackAlphaLookupTable());
    }

    if( value == "greenBlackAlpha") {
	d->collection->SyncSetLookupTable(vtkLookupTableManager::GetGreenBlackAlphaLookupTable());
    }

    if (value == "redBlackAlpha") {
	d->collection->SyncSetLookupTable(vtkLookupTableManager::GetRedBlackAlphaLookupTable());
    }

    if (value == "Muscles&Bones") {
	d->collection->SyncSetLookupTable(vtkLookupTableManager::GetVRMusclesBonesLookupTable());
    }

    if (value == "Stern") {
	d->collection->SyncSetLookupTable(vtkLookupTableManager::GetSternLookupTable());
    }

    if (value == "Red Vessels") {
	d->collection->SyncSetLookupTable(vtkLookupTableManager::GetVRRedVesselsLookupTable());
    }

    if (value == "Bones") {
	d->collection->SyncSetLookupTable(vtkLookupTableManager::GetVRBonesLookupTable());
    }
}


void v3dView::onBackgroundLookupTablePropertySet(QString value)
{
  /*
    if (value == "Default")
	d->view2D->SetBGLookupTable(vtkLookupTableManager::GetBWLookupTable());

    if (value == "Black&White")
	d->view2D->SetBGLookupTable(vtkLookupTableManager::GetBWLookupTable());

    if (value == "Black&WhiteInversed")
	d->view2D->SetBGLookupTable(vtkLookupTableManager::GetBWInverseLookupTable());

    if (value == "Spectrum")
	d->view2D->SetBGLookupTable(vtkLookupTableManager::GetSpectrumLookupTable());

    if (value == "HotMetal")
	d->view2D->SetBGLookupTable(vtkLookupTableManager::GetHotMetalLookupTable());

    if (value == "GE")
	d->view2D->SetBGLookupTable(vtkLookupTableManager::GetGEColorLookupTable());

    if (value == "Loni")
	d->view2D->SetBGLookupTable(vtkLookupTableManager::GetLONILookupTable());

    if (value == "Loni2")
	d->view2D->SetBGLookupTable(vtkLookupTableManager::GetLONI2LookupTable());

    if (value == "Asymmetry")
	d->view2D->SetBGLookupTable(vtkLookupTableManager::GetAsymmetryLookupTable());

    if (value == "PValue")
	d->view2D->SetBGLookupTable(vtkLookupTableManager::GetPValueLookupTable());

    if (value == "blueBlackAlpha")
	d->view2D->SetBGLookupTable(vtkLookupTableManager::GetBlueBlackAlphaLookupTable());

    if( value == "greenBlackAlpha")
	d->view2D->SetBGLookupTable(vtkLookupTableManager::GetGreenBlackAlphaLookupTable());

    if (value == "redBlackAlpha")
	d->view2D->SetBGLookupTable(vtkLookupTableManager::GetRedBlackAlphaLookupTable());
  */
}


void v3dView::onOpacityPropertySet(QString value)
{
    bool ok; double opacity = value.toDouble(&ok);

    if (ok) {
	d->view2DAxial->GetImageActor()->SetOpacity(opacity);
	d->view2DSagittal->GetImageActor()->SetOpacity(opacity);
	d->view2DCoronal->GetImageActor()->SetOpacity(opacity);
    }
    else
	qDebug("Error: cannot convert QString value to a double");
}

void v3dView::onShowAxisPropertySet(QString value)
{
    if (value == "true")
	d->collection->SyncSetShowImageAxis(1);

    if (value == "false")
	d->collection->SyncSetShowImageAxis(0);
}

void v3dView::onLeftClickInteractionPropertySet(QString value)
{
    if (value == "Zooming") {
        d->view2DAxial->SetLeftButtonInteractionStyle(vtkInteractorStyleImageView2D::InteractionTypeZoom);
	d->view2DSagittal->SetLeftButtonInteractionStyle(vtkInteractorStyleImageView2D::InteractionTypeZoom);
	d->view2DCoronal->SetLeftButtonInteractionStyle(vtkInteractorStyleImageView2D::InteractionTypeZoom);
    }

    if (value == "Windowing") {
        d->view2DAxial->SetLeftButtonInteractionStyle(vtkInteractorStyleImageView2D::InteractionTypeWindowLevel);
	d->view2DSagittal->SetLeftButtonInteractionStyle(vtkInteractorStyleImageView2D::InteractionTypeWindowLevel);
	d->view2DCoronal->SetLeftButtonInteractionStyle(vtkInteractorStyleImageView2D::InteractionTypeWindowLevel);
    }
    

    if (value == "Slicing") {
        d->view2DAxial->SetLeftButtonInteractionStyle(vtkInteractorStyleImageView2D::InteractionTypeSlice);
	d->view2DSagittal->SetLeftButtonInteractionStyle(vtkInteractorStyleImageView2D::InteractionTypeSlice);
	d->view2DCoronal->SetLeftButtonInteractionStyle(vtkInteractorStyleImageView2D::InteractionTypeSlice);
    }

    if (value == "Measuring") {
        d->view2DAxial->ShowDistanceWidgetOn();
	d->view2DSagittal->ShowDistanceWidgetOn();
	d->view2DCoronal->ShowDistanceWidgetOn();
    }
    else {
        d->view2DAxial->ShowDistanceWidgetOff();
	d->view2DSagittal->ShowDistanceWidgetOff();
	d->view2DCoronal->ShowDistanceWidgetOff();
    }
}

void v3dView::onPresetPropertySet (QString value)
{
  //double white[3] = {1.0,1.0,1.0};
    
    if( value == "VR Muscles&Bones" ) {

      this->setProperty ("LookupTable", "Muscles&Bones");

      double color[3] = {0.0, 0.0, 0.0};

      if ( d->currentView ) {
	d->currentView->SetBackground( color );
	d->currentView->SetColorWindow (337.0);
	d->currentView->SetColorLevel (1237.0);
	//d->collection->SyncSetTextColor ( white );
	//d->collection->SyncSetAboutData ("VR Muscles - Bones - Powered by magic Pedro");
      }
    }

    if( value == "Vascular I" ) {

      this->setProperty ("LookupTable", "Stern");

      double color[3] = {0.0, 0.0, 0.0};
      
      d->collection->SyncSetBackground( color );
      d->collection->SyncSetColorWindow (388.8);
      d->collection->SyncSetColorLevel (362.9);
      //d->collection->SyncSetTextColor ( white );
      //d->view->SetAboutData ("Vascular - Powered by magic Pedro");
    }

    if( value == "Vascular II" ) {

      this->setProperty ("LookupTable", "Red Vessels");

      double color[3] = {0.0, 0.0, 0.0};
      
      d->collection->SyncSetBackground( color );
      d->collection->SyncSetColorWindow (189.6);
      d->collection->SyncSetColorLevel (262.3);

      //d->collection->SyncSetTextColor ( white );
      //d->view->SetAboutData ("Vascular II - Powered by magic Pedro");
    }

    if( value == "Vascular III" ) {

      this->setProperty ("LookupTable", "Red Vessels");

      double color[3] = {0.0, 0.0, 0.0};
      
      d->collection->SyncSetBackground( color );
      d->collection->SyncSetColorWindow (284.4);
      d->collection->SyncSetColorLevel (341.7);
      //d->collection->SyncSetTextColor ( white );
      //d->view->SetAboutData ("Vascular III - Powered by magic Pedro");
    }
    
    if( value == "Vascular IV" ) {

      this->setProperty ("LookupTable", "Red Vessels");

      double color[3] = {0.0, 0.0, 0.0};
      
      d->collection->SyncSetBackground( color );
      d->collection->SyncSetColorWindow (272.5);
      d->collection->SyncSetColorLevel (310.9);
      //d->collection->SyncSetTextColor ( white );
      //d->view->SetAboutData ("Vascular IV - Powered by magic Pedro");
    }

    if( value == "Standard" ) {

      this->setProperty ("LookupTable", "Muscles&Bones");

      double color[3] = {0.0, 0.0, 0.0};
      
      d->collection->SyncSetBackground( color );
      d->collection->SyncSetColorWindow (243.7);
      d->collection->SyncSetColorLevel (199.6);
      //d->collection->SyncSetTextColor ( white );
      //d->view->SetAboutData ("Standard - Powered by magic Pedro");
    }

    if( value == "Soft" ) {

      this->setProperty ("LookupTable", "Bones");

      double color[3] = {0.0, 0.0, 0.0};
      
      d->collection->SyncSetBackground( color );
      d->collection->SyncSetColorWindow (133.5);
      d->collection->SyncSetColorLevel (163.4);
      //d->collection->SyncSetTextColor ( white );
      //d->view->SetAboutData ("Soft - Powered by magic Pedro");
    }

    if( value == "Soft on White" ) {

      this->setProperty ("LookupTable", "Muscles&Bones");

      double color[3] = {1.0,0.98820477724075317,0.98814374208450317};
      
      d->collection->SyncSetBackground( color );
      d->collection->SyncSetColorWindow (449.3);
      d->collection->SyncSetColorLevel (372.8);
      //d->view->SetAboutData ("Soft on White - Powered by magic Pedro");
    }

    if( value == "Soft on Blue" ) {

      this->setProperty ("LookupTable", "Muscles&Bones");

      double color[3]={0.0, 0.27507439255714417, 0.26398107409477234};      
      
      d->collection->SyncSetBackground( color );
      d->collection->SyncSetColorWindow (449.3);
      d->collection->SyncSetColorLevel (372.8);
      //d->collection->SetAboutData ("Soft on Blue - Powered by magic Pedro");
    }

    if( value == "Red on White" ) {

      this->setProperty ("LookupTable", "Red Vessels");

      double color[3]={1.0, 0.98820477724075317, 0.98814374208450317};
	
      d->collection->SyncSetBackground( color );
      d->collection->SyncSetColorWindow (449.3);
      d->collection->SyncSetColorLevel (372.8);
      //d->view->SetAboutData ("Red on White - Powered by magic Pedro");
    }

    if( value == "Glossy" ) {

      this->setProperty ("LookupTable", "Bones");

      double color[3] = {0.0, 0.0, 0.0};
      
      d->collection->SyncSetBackground( color );
      d->collection->SyncSetColorWindow (133.5);
      d->collection->SyncSetColorLevel (163.4);
      //d->collection->SyncSetTextColor ( white );
      //d->view->SetAboutData ("Glossy - Powered by magic Pedro");
    }

}

void v3dView::onCroppingPropertySet (QString value)
{
    if ( value=="true" ) {
        d->view3D->SetCroppingModeToOutside();
	d->view3D->SetShowBoxWidget ( 1 );
    }
    else {
      d->view3D->SetCroppingModeToOff ();
      d->view3D->SetShowBoxWidget ( 0 );
    }
}

void v3dView::onMousePressEvent(QMouseEvent *event)
{
    if(event->button() == Qt::RightButton) {
        d->menu->popup (event->globalPos());
    }
}

void v3dView::onZSliderValueChanged (int value)
{
    if (d->orientation=="3D" || !d->currentView)
        return;

    d->observer->Lock();
    if( vtkImageView2D *view = vtkImageView2D::SafeDownCast(d->currentView) ) {
        view->SetSlice (value);
        d->currentView->Render();
    }
    d->observer->UnLock();
}

void v3dView::onMenuAxialTriggered (void)
{
    if(qApp->arguments().contains("--stereo"))
        d->vtkWidget->GetRenderWindow()->SetStereoRender(0);

    this->setProperty("Orientation", "Axial");
    d->view2DAxial->Render();
}


void v3dView::onMenuCoronalTriggered (void)
{
    if(qApp->arguments().contains("--stereo"))
        d->vtkWidget->GetRenderWindow()->SetStereoRender(0);

    this->setProperty("Orientation", "Coronal");
    d->view2DCoronal->Render();
}


void v3dView::onMenuSagittalTriggered (void)
{
    if(qApp->arguments().contains("--stereo"))
        d->vtkWidget->GetRenderWindow()->SetStereoRender(0);

    this->setProperty("Orientation", "Sagittal");
    d->view2DSagittal->Render();
}

void v3dView::onMenu3DVRTriggered (void)
{
    if(qApp->arguments().contains("--stereo"))
        d->vtkWidget->GetRenderWindow()->SetStereoRender(1);

    this->setProperty ("Orientation", "3D");
    this->setProperty ("Mode", "VR");    
    d->view3D->Render();
}

void v3dView::onMenu3DMPRTriggered (void)
{
    if(qApp->arguments().contains("--stereo"))
        d->vtkWidget->GetRenderWindow()->SetStereoRender(1);

    this->setProperty("Orientation", "3D");
    this->setProperty("Mode", "MPR");
    d->view3D->Render();
}

void v3dView::onMenu3DMaxIPTriggered (void)
{
    if(qApp->arguments().contains("--stereo"))
        d->vtkWidget->GetRenderWindow()->SetStereoRender(1);

    this->setProperty("Orientation", "3D");
    this->setProperty("Mode", "MIP - Maximum");
    d->view3D->Render();
}

void v3dView::onMenu3DMinIPTriggered (void)
{
    if(qApp->arguments().contains("--stereo"))
        d->vtkWidget->GetRenderWindow()->SetStereoRender(1);

    this->setProperty("Orientation", "3D");
    this->setProperty("Mode", "MIP - Minimum");
    d->view3D->Render();
}

void v3dView::onMenuZoomTriggered (void)
{
    this->setProperty ("LeftClickInteraction", "Zooming");
}

void v3dView::onMenuWindowLevelTriggered (void)
{
    this->setProperty ("LeftClickInteraction", "Windowing");
}

void v3dView::onVRQualitySet (int value)
{
    d->view3D->SetVRQuality ( (float)(value) / 100.0 );
}

// /////////////////////////////////////////////////////////////////
// Type instanciation
// /////////////////////////////////////////////////////////////////

dtkAbstractView *createV3dView(void)
{
    return new v3dView;
}
