// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#ifndef ITKDATAIMAGEWRITERPLUGIN_H
#define ITKDATAIMAGEWRITERPLUGIN_H

#include <dtkCore/dtkPlugin.h>

#include "itkDataImageWriterPluginExport.h"

class ITKDATAIMAGEWRITERPLUGIN_EXPORT itkDataImageWriterPluginPrivate;

class ITKDATAIMAGEWRITERPLUGIN_EXPORT itkDataImageWriterPlugin : public dtkPlugin
{
    Q_OBJECT
    Q_INTERFACES(dtkPlugin)

public:
            itkDataImageWriterPlugin(QObject *parent = 0);
    ~itkDataImageWriterPlugin(void);

    virtual bool initialize(void);
    virtual bool uninitialize(void);

    virtual QString name(void) const;
    virtual QString description(void) const;

    virtual QStringList tags(void) const;
    virtual QStringList types(void) const;

private:
    itkDataImageWriterPluginPrivate *d;
};

#endif
