// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#ifndef ITKDATAIMAGEWRITER_H
#define ITKDATAIMAGEWRITER_H

#include <dtkCore/dtkAbstractDataWriter.h>

#include "itkDataImageWriterPluginExport.h"

class itkDataImageChar3WriterPrivate;

class ITKDATAIMAGEWRITERPLUGIN_EXPORT itkDataImageChar3Writer : public dtkAbstractDataWriter
{
    Q_OBJECT

public:
             itkDataImageChar3Writer(void);
    virtual ~itkDataImageChar3Writer(void);

    virtual QString description(void) const;
    virtual QStringList handled(void) const;
    static bool registered(void);

public slots:
    bool write(QString path);
    bool canWrite (QString path);
    
private:
    itkDataImageChar3WriterPrivate *d;
};

dtkAbstractDataWriter *createItkDataImageChar3Writer(void);


class itkDataImageUChar3WriterPrivate;

class ITKDATAIMAGEWRITERPLUGIN_EXPORT itkDataImageUChar3Writer : public dtkAbstractDataWriter
{
    Q_OBJECT

public:
             itkDataImageUChar3Writer(void);
    virtual ~itkDataImageUChar3Writer(void);

    virtual QString description(void) const;
    virtual QStringList handled(void) const;
    static bool registered(void);

public slots:
    bool write(QString path);
    bool canWrite (QString path);
    
private:
    itkDataImageUChar3WriterPrivate *d;
};

dtkAbstractDataWriter *createItkDataImageUChar3Writer(void);



class itkDataImageShort3WriterPrivate;

class ITKDATAIMAGEWRITERPLUGIN_EXPORT itkDataImageShort3Writer : public dtkAbstractDataWriter
{
    Q_OBJECT

public:
             itkDataImageShort3Writer(void);
    virtual ~itkDataImageShort3Writer(void);

    virtual QString description(void) const;
    virtual QStringList handled(void) const;
    static bool registered(void);

public slots:
    bool write(QString path);
    bool canWrite (QString path);
    
private:
    itkDataImageShort3WriterPrivate *d;
};

dtkAbstractDataWriter *createItkDataImageShort3Writer(void);



class itkDataImageUShort3WriterPrivate;

class ITKDATAIMAGEWRITERPLUGIN_EXPORT itkDataImageUShort3Writer : public dtkAbstractDataWriter
{
    Q_OBJECT

public:
             itkDataImageUShort3Writer(void);
    virtual ~itkDataImageUShort3Writer(void);

    virtual QString description(void) const;
    virtual QStringList handled(void) const;
    static bool registered(void);

public slots:
    bool write(QString path);
    bool canWrite (QString path);
    
private:
    itkDataImageUShort3WriterPrivate *d;
};

dtkAbstractDataWriter *createItkDataImageUShort3Writer(void);



class itkDataImageInt3WriterPrivate;

class ITKDATAIMAGEWRITERPLUGIN_EXPORT itkDataImageInt3Writer : public dtkAbstractDataWriter
{
    Q_OBJECT

public:
             itkDataImageInt3Writer(void);
    virtual ~itkDataImageInt3Writer(void);

    virtual QString description(void) const;
    virtual QStringList handled(void) const;
    static bool registered(void);

public slots:
    bool write(QString path);
    bool canWrite (QString path);
    
private:
    itkDataImageInt3WriterPrivate *d;
};

dtkAbstractDataWriter *createItkDataImageInt3Writer(void);



class itkDataImageUInt3WriterPrivate;

class ITKDATAIMAGEWRITERPLUGIN_EXPORT itkDataImageUInt3Writer : public dtkAbstractDataWriter
{
    Q_OBJECT

public:
             itkDataImageUInt3Writer(void);
    virtual ~itkDataImageUInt3Writer(void);

    virtual QString description(void) const;
    virtual QStringList handled(void) const;
    static bool registered(void);

public slots:
    bool write(QString path);
    bool canWrite (QString path);
    
private:
    itkDataImageUInt3WriterPrivate *d;
};

dtkAbstractDataWriter *createItkDataImageUInt3Writer(void);



class itkDataImageLong3WriterPrivate;

class ITKDATAIMAGEWRITERPLUGIN_EXPORT itkDataImageLong3Writer : public dtkAbstractDataWriter
{
    Q_OBJECT

public:
             itkDataImageLong3Writer(void);
    virtual ~itkDataImageLong3Writer(void);

    virtual QString description(void) const;
    virtual QStringList handled(void) const;
    static bool registered(void);

public slots:
    bool write(QString path);
    bool canWrite (QString path);
    
private:
    itkDataImageLong3WriterPrivate *d;
};

dtkAbstractDataWriter *createItkDataImageLong3Writer(void);



class itkDataImageULong3WriterPrivate;

class ITKDATAIMAGEWRITERPLUGIN_EXPORT itkDataImageULong3Writer : public dtkAbstractDataWriter
{
    Q_OBJECT

public:
             itkDataImageULong3Writer(void);
    virtual ~itkDataImageULong3Writer(void);

    virtual QString description(void) const;
    virtual QStringList handled(void) const;
    static bool registered(void);

public slots:
    bool write(QString path);
    bool canWrite (QString path);
    
private:
    itkDataImageULong3WriterPrivate *d;
};

dtkAbstractDataWriter *createItkDataImageULong3Writer(void);



class itkDataImageFloat3WriterPrivate;

class ITKDATAIMAGEWRITERPLUGIN_EXPORT itkDataImageFloat3Writer : public dtkAbstractDataWriter
{
    Q_OBJECT

public:
             itkDataImageFloat3Writer(void);
    virtual ~itkDataImageFloat3Writer(void);

    virtual QString description(void) const;
    virtual QStringList handled(void) const;
    static bool registered(void);

public slots:
    bool write(QString path);
    bool canWrite (QString path);
    
private:
    itkDataImageFloat3WriterPrivate *d;
};

dtkAbstractDataWriter *createItkDataImageFloat3Writer(void);



class itkDataImageDouble3WriterPrivate;

class ITKDATAIMAGEWRITERPLUGIN_EXPORT itkDataImageDouble3Writer : public dtkAbstractDataWriter
{
    Q_OBJECT

public:
             itkDataImageDouble3Writer(void);
    virtual ~itkDataImageDouble3Writer(void);

    virtual QString description(void) const;
    virtual QStringList handled(void) const;
    static bool registered(void);

public slots:
    bool write(QString path);
    bool canWrite (QString path);
    
private:
    itkDataImageDouble3WriterPrivate *d;
};

dtkAbstractDataWriter *createItkDataImageDouble3Writer(void);

#endif
