set(CTEST_PROJECT_NAME "Medular")
set(NIGHTLY_START_TIME "21:00:00 EST")
set(CTEST_DROP_METHOD "http")
set(CTEST_DROP_SITE "cdash.inria.fr")
set(CTEST_DROP_LOCATION "/CDash/submit.php?project=Medular")
set(CTEST_DROP_SITE_CDASH TRUE)
set(CTEST_CTEST_UPDATE_TYPE "git")
set(CTEST_UPDATE_COMMAND "git")
