// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#ifndef MEDITKEXPORT_H
#define MEDITKEXPORT_H

#ifdef WIN32
    #ifdef medItk_EXPORTS
        #define MEDITK_EXPORT __declspec(dllexport) 
    #else
        #define MEDITK_EXPORT __declspec(dllimport) 
    #endif
#else
    #define MEDITK_EXPORT
#endif

#endif

