set(PYTHON_VERSION_MINOR 8)
set(PYTHON_MAIN_LIBRARY libpython3.8.so)
set(PYTHON_HEADERS_DIR headers/python3.8)
set(PYTHON_LIBRARIES_DIR libraries/python3.8)
set(PYTHON_MODULES_DIR modules/python3.8)
set(PYTHON_LICENSE_FILE LICENSE.txt)

set(PYTHON_HEADERS
    ImDib.h
    ImPlatform.h
    Imaging.h
    ImagingUtils.h
    Python-ast.h
    Python.h
    abstract.h
    asdl.h
    ast.h
    bitset.h
    bltinmodule.h
    boolobject.h
    bytearrayobject.h
    bytes_methods.h
    bytesobject.h
    cellobject.h
    ceval.h
    classobject.h
    code.h
    codecs.h
    compile.h
    complexobject.h
    context.h
    cpython
    cpython/abstract.h
    cpython/dictobject.h
    cpython/fileobject.h
    cpython/initconfig.h
    cpython/interpreteridobject.h
    cpython/object.h
    cpython/objimpl.h
    cpython/pyerrors.h
    cpython/pylifecycle.h
    cpython/pymem.h
    cpython/pystate.h
    cpython/sysmodule.h
    cpython/traceback.h
    cpython/tupleobject.h
    cpython/unicodeobject.h
    datetime.h
    descrobject.h
    dictobject.h
    dtoa.h
    dynamic_annotations.h
    enumobject.h
    errcode.h
    eval.h
    fileobject.h
    fileutils.h
    floatobject.h
    frameobject.h
    funcobject.h
    genobject.h
    graminit.h
    grammar.h
    import.h
    internal
    internal/pycore_accu.h
    internal/pycore_atomic.h
    internal/pycore_ceval.h
    internal/pycore_code.h
    internal/pycore_condvar.h
    internal/pycore_context.h
    internal/pycore_fileutils.h
    internal/pycore_getopt.h
    internal/pycore_gil.h
    internal/pycore_hamt.h
    internal/pycore_initconfig.h
    internal/pycore_object.h
    internal/pycore_pathconfig.h
    internal/pycore_pyerrors.h
    internal/pycore_pyhash.h
    internal/pycore_pylifecycle.h
    internal/pycore_pymem.h
    internal/pycore_pystate.h
    internal/pycore_traceback.h
    internal/pycore_tupleobject.h
    internal/pycore_warnings.h
    interpreteridobject.h
    intrcheck.h
    iterobject.h
    listobject.h
    longintrepr.h
    longobject.h
    marshal.h
    memoryobject.h
    methodobject.h
    modsupport.h
    moduleobject.h
    namespaceobject.h
    node.h
    object.h
    objimpl.h
    odictobject.h
    opcode.h
    osdefs.h
    osmodule.h
    parsetok.h
    patchlevel.h
    picklebufobject.h
    py_curses.h
    pyarena.h
    pycapsule.h
    pyconfig.h
    pyctype.h
    pydebug.h
    pydtrace.h
    pyerrors.h
    pyexpat.h
    pyfpe.h
    pyhash.h
    pylifecycle.h
    pymacconfig.h
    pymacro.h
    pymath.h
    pymem.h
    pyport.h
    pystate.h
    pystrcmp.h
    pystrhex.h
    pystrtod.h
    pythonrun.h
    pythread.h
    pytime.h
    rangeobject.h
    setobject.h
    sliceobject.h
    structmember.h
    structseq.h
    symtable.h
    sysmodule.h
    token.h
    traceback.h
    tracemalloc.h
    tupleobject.h
    typeslots.h
    ucnhash.h
    unicodeobject.h
    warnings.h
    weakrefobject.h
    )

set(PYTHON_LIBRARIES
    _asyncio.cpython-38-x86_64-linux-gnu.so
    _bz2.cpython-38-x86_64-linux-gnu.so
    _codecs_cn.cpython-38-x86_64-linux-gnu.so
    _codecs_hk.cpython-38-x86_64-linux-gnu.so
    _codecs_iso2022.cpython-38-x86_64-linux-gnu.so
    _codecs_jp.cpython-38-x86_64-linux-gnu.so
    _codecs_kr.cpython-38-x86_64-linux-gnu.so
    _codecs_tw.cpython-38-x86_64-linux-gnu.so
    _contextvars.cpython-38-x86_64-linux-gnu.so
    _crypt.cpython-38-x86_64-linux-gnu.so
    _ctypes.cpython-38-x86_64-linux-gnu.so
    _ctypes_test.cpython-38-x86_64-linux-gnu.so
    _curses.cpython-38-x86_64-linux-gnu.so
    _curses_panel.cpython-38-x86_64-linux-gnu.so
    _dbm.cpython-38-x86_64-linux-gnu.so
    _decimal.cpython-38-x86_64-linux-gnu.so
    _gdbm.cpython-38-x86_64-linux-gnu.so
    _hashlib.cpython-38-x86_64-linux-gnu.so
    _json.cpython-38-x86_64-linux-gnu.so
    _lsprof.cpython-38-x86_64-linux-gnu.so
    _lzma.cpython-38-x86_64-linux-gnu.so
    _multibytecodec.cpython-38-x86_64-linux-gnu.so
    _multiprocessing.cpython-38-x86_64-linux-gnu.so
    _opcode.cpython-38-x86_64-linux-gnu.so
    _posixshmem.cpython-38-x86_64-linux-gnu.so
    _queue.cpython-38-x86_64-linux-gnu.so
    _sqlite3.cpython-38-x86_64-linux-gnu.so
    _ssl.cpython-38-x86_64-linux-gnu.so
    _testbuffer.cpython-38-x86_64-linux-gnu.so
    _testcapi.cpython-38-x86_64-linux-gnu.so
    _testimportmultiple.cpython-38-x86_64-linux-gnu.so
    _testinternalcapi.cpython-38-x86_64-linux-gnu.so
    _testmultiphase.cpython-38-x86_64-linux-gnu.so
    _uuid.cpython-38-x86_64-linux-gnu.so
    _xxsubinterpreters.cpython-38-x86_64-linux-gnu.so
    _xxtestfuzz.cpython-38-x86_64-linux-gnu.so
    audioop.cpython-38-x86_64-linux-gnu.so
    libpython3.8.so
    mmap.cpython-38-x86_64-linux-gnu.so
    nis.cpython-38-x86_64-linux-gnu.so
    ossaudiodev.cpython-38-x86_64-linux-gnu.so
    parser.cpython-38-x86_64-linux-gnu.so
    readline.cpython-38-x86_64-linux-gnu.so
    resource.cpython-38-x86_64-linux-gnu.so
    termios.cpython-38-x86_64-linux-gnu.so
    xxlimited.cpython-38-x86_64-linux-gnu.so
    )

set(PYTHON_MODULES
    __future__.py
    __phello__.foo.py
    _bootlocale.py
    _collections_abc.py
    _compat_pickle.py
    _compression.py
    _dummy_thread.py
    _markupbase.py
    _osx_support.py
    _py_abc.py
    _pydecimal.py
    _pyio.py
    _sitebuiltins.py
    _strptime.py
    _threading_local.py
    _weakrefset.py
    abc.py
    aifc.py
    antigravity.py
    argparse.py
    ast.py
    asynchat.py
    asyncore.py
    base64.py
    bdb.py
    binhex.py
    bisect.py
    bz2.py
    cProfile.py
    calendar.py
    cgi.py
    cgitb.py
    chunk.py
    cmd.py
    code.py
    codecs.py
    codeop.py
    colorsys.py
    compileall.py
    configparser.py
    contextlib.py
    contextvars.py
    copy.py
    copyreg.py
    crypt.py
    csv.py
    dataclasses.py
    datetime.py
    decimal.py
    difflib.py
    dis.py
    doctest.py
    dummy_threading.py
    encodings___init__.py
    encodings_aliases.py
    encodings_ascii.py
    encodings_base64_codec.py
    encodings_big5.py
    encodings_big5hkscs.py
    encodings_bz2_codec.py
    encodings_charmap.py
    encodings_cp037.py
    encodings_cp1006.py
    encodings_cp1026.py
    encodings_cp1125.py
    encodings_cp1140.py
    encodings_cp1250.py
    encodings_cp1251.py
    encodings_cp1252.py
    encodings_cp1253.py
    encodings_cp1254.py
    encodings_cp1255.py
    encodings_cp1256.py
    encodings_cp1257.py
    encodings_cp1258.py
    encodings_cp273.py
    encodings_cp424.py
    encodings_cp437.py
    encodings_cp500.py
    encodings_cp720.py
    encodings_cp737.py
    encodings_cp775.py
    encodings_cp850.py
    encodings_cp852.py
    encodings_cp855.py
    encodings_cp856.py
    encodings_cp857.py
    encodings_cp858.py
    encodings_cp860.py
    encodings_cp861.py
    encodings_cp862.py
    encodings_cp863.py
    encodings_cp864.py
    encodings_cp865.py
    encodings_cp866.py
    encodings_cp869.py
    encodings_cp874.py
    encodings_cp875.py
    encodings_cp932.py
    encodings_cp949.py
    encodings_cp950.py
    encodings_euc_jis_2004.py
    encodings_euc_jisx0213.py
    encodings_euc_jp.py
    encodings_euc_kr.py
    encodings_gb18030.py
    encodings_gb2312.py
    encodings_gbk.py
    encodings_hex_codec.py
    encodings_hp_roman8.py
    encodings_hz.py
    encodings_idna.py
    encodings_iso2022_jp.py
    encodings_iso2022_jp_1.py
    encodings_iso2022_jp_2.py
    encodings_iso2022_jp_2004.py
    encodings_iso2022_jp_3.py
    encodings_iso2022_jp_ext.py
    encodings_iso2022_kr.py
    encodings_iso8859_1.py
    encodings_iso8859_10.py
    encodings_iso8859_11.py
    encodings_iso8859_13.py
    encodings_iso8859_14.py
    encodings_iso8859_15.py
    encodings_iso8859_16.py
    encodings_iso8859_2.py
    encodings_iso8859_3.py
    encodings_iso8859_4.py
    encodings_iso8859_5.py
    encodings_iso8859_6.py
    encodings_iso8859_7.py
    encodings_iso8859_8.py
    encodings_iso8859_9.py
    encodings_johab.py
    encodings_koi8_r.py
    encodings_koi8_t.py
    encodings_koi8_u.py
    encodings_kz1048.py
    encodings_latin_1.py
    encodings_mac_arabic.py
    encodings_mac_centeuro.py
    encodings_mac_croatian.py
    encodings_mac_cyrillic.py
    encodings_mac_farsi.py
    encodings_mac_greek.py
    encodings_mac_iceland.py
    encodings_mac_latin2.py
    encodings_mac_roman.py
    encodings_mac_romanian.py
    encodings_mac_turkish.py
    encodings_mbcs.py
    encodings_oem.py
    encodings_palmos.py
    encodings_ptcp154.py
    encodings_punycode.py
    encodings_quopri_codec.py
    encodings_raw_unicode_escape.py
    encodings_rot_13.py
    encodings_shift_jis.py
    encodings_shift_jis_2004.py
    encodings_shift_jisx0213.py
    encodings_tis_620.py
    encodings_undefined.py
    encodings_unicode_escape.py
    encodings_utf_16.py
    encodings_utf_16_be.py
    encodings_utf_16_le.py
    encodings_utf_32.py
    encodings_utf_32_be.py
    encodings_utf_32_le.py
    encodings_utf_7.py
    encodings_utf_8.py
    encodings_utf_8_sig.py
    encodings_uu_codec.py
    encodings_zlib_codec.py
    enum.py
    filecmp.py
    fileinput.py
    fnmatch.py
    formatter.py
    fractions.py
    ftplib.py
    functools.py
    genericpath.py
    getopt.py
    getpass.py
    gettext.py
    glob.py
    gzip.py
    hashlib.py
    heapq.py
    hmac.py
    imaplib.py
    imghdr.py
    imp.py
    inspect.py
    io.py
    ipaddress.py
    keyword.py
    linecache.py
    locale.py
    lzma.py
    mailbox.py
    mailcap.py
    mimetypes.py
    modulefinder.py
    netrc.py
    nntplib.py
    ntpath.py
    nturl2path.py
    numbers.py
    opcode.py
    operator.py
    optparse.py
    os.py
    packages.zip
    pathlib.py
    pdb.py
    pickle.py
    pickletools.py
    pipes.py
    pkgutil.py
    platform.py
    plistlib.py
    poplib.py
    posixpath.py
    pprint.py
    profile.py
    pstats.py
    pty.py
    py_compile.py
    pyclbr.py
    pydoc.py
    queue.py
    quopri.py
    random.py
    re.py
    reprlib.py
    rlcompleter.py
    runpy.py
    sched.py
    secrets.py
    selectors.py
    shelve.py
    shlex.py
    shutil.py
    signal.py
    site.py
    smtpd.py
    smtplib.py
    sndhdr.py
    socket.py
    socketserver.py
    sre_compile.py
    sre_constants.py
    sre_parse.py
    ssl.py
    stat.py
    statistics.py
    string.py
    stringprep.py
    struct.py
    subprocess.py
    sunau.py
    symbol.py
    symtable.py
    sysconfig.py
    tabnanny.py
    tarfile.py
    telnetlib.py
    tempfile.py
    textwrap.py
    this.py
    threading.py
    timeit.py
    token.py
    tokenize.py
    trace.py
    traceback.py
    tracemalloc.py
    tty.py
    turtle.py
    types.py
    typing.py
    uu.py
    uuid.py
    warnings.py
    wave.py
    weakref.py
    webbrowser.py
    xdrlib.py
    zipapp.py
    zipfile.py
    zipimport.py
    )
