// /////////////////////////////////////////////////////////////////
// Generated by medPluginGenerator
// /////////////////////////////////////////////////////////////////

#pragma once

#include <medRegistrationAbstractToolBox.h>
#include "%1PluginExport.h"

class %1ToolBoxPrivate;

class %2PLUGIN_EXPORT %1ToolBox : public medRegistrationAbstractToolBox
{
    Q_OBJECT
    
public:
    %1ToolBox(QWidget *parent = 0);
    ~%1ToolBox(void);
    
public:
    static bool registered(void);
    
public slots:
    void run(void);
    
private:
    %1ToolBoxPrivate *d;
};


