// /////////////////////////////////////////////////////////////////
// Generated by medPluginGenerator
// /////////////////////////////////////////////////////////////////

#ifndef %2TOOLBOX_H
#define %2TOOLBOX_H

#include <medToolBoxRegistrationCustom.h>
#include "%1PluginExport.h"

namespace %3
{
    
    class %1ToolBoxPrivate;
    
    class %2PLUGIN_EXPORT %1ToolBox : public medToolBoxRegistrationCustom
    {
        Q_OBJECT
        
    public:
        %1ToolBox(QWidget *parent = 0);
        ~%1ToolBox(void);
        
    public:
        static bool registered(void);
        
        public slots:
        void run(void);
        
    private:
        %1ToolBoxPrivate *d;
    };
    
} // end namespace %3

#endif
