// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#pragma once

#include <dtkCore/dtkPlugin.h>

#include "itkDataDiffusionGradientListPluginExport.h"

class ITKDATADIFFUSIONGRADIENTLISTPLUGIN_EXPORT itkDataDiffusionGradientListPluginPrivate;

class ITKDATADIFFUSIONGRADIENTLISTPLUGIN_EXPORT itkDataDiffusionGradientListPlugin : public dtkPlugin
{
    Q_OBJECT
    Q_INTERFACES(dtkPlugin)

public:
     itkDataDiffusionGradientListPlugin(QObject *parent = 0);
    ~itkDataDiffusionGradientListPlugin(void);

    virtual bool initialize(void);
    virtual bool uninitialize(void);

    virtual QString name(void) const;
    virtual QString description(void) const;
    virtual QString identifier(void) const;
    virtual QString version(void) const;
    virtual QStringList tags(void) const;
    virtual QStringList types(void) const;

private:
     itkDataDiffusionGradientListPluginPrivate *d;
};


