set(CTEST_PROJECT_NAME "vtkINRIA3D")
set(CTEST_NIGHTLY_START_TIME "00:00:00 EST")

set(CTEST_DROP_METHOD "http")
set(CTEST_DROP_SITE "cdash.inria.fr")
set(CTEST_DROP_LOCATION "/CDash/submit.php?project=vtkINRIA3D")
set(CTEST_DROP_SITE_CDASH TRUE)
