// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#pragma once

#include <dtkCore/dtkAbstractProcess.h>
#include <dtkCore/dtkAbstractData.h>

#include "ITKProcessExamplePluginExport.h"

class ITKProcessExamplePrivate;
class dtkAbstractData;

class ITKPROCESSEXAMPLEPLUGIN_EXPORT ITKProcessExample : public dtkAbstractProcess
{
    Q_OBJECT

public:
             ITKProcessExample();
    virtual ~ITKProcessExample();

    virtual QString description() const;

    static bool registered();

public slots:

    void setInput(dtkAbstractData *data);
    void setParameter(double  data, int channel);
    int update();
    dtkAbstractData *output();

    //bool write(QString file);

private:
    ITKProcessExamplePrivate *d;
};

dtkAbstractProcess *createITKProcessExample();


