// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#ifndef ITKDATASHIMAGEREADERPLUGIN_H
#define ITKDATASHIMAGEREADERPLUGIN_H

#include <dtkCore/dtkPlugin.h>

#include "itkDataSHImageReaderPluginExport.h"

class ITKDATASHIMAGEREADERPLUGIN_EXPORT itkDataSHImageReaderPluginPrivate;

class ITKDATASHIMAGEREADERPLUGIN_EXPORT itkDataSHImageReaderPlugin : public dtkPlugin
{
    Q_OBJECT
    Q_INTERFACES(dtkPlugin)

public:
     itkDataSHImageReaderPlugin(QObject *parent = 0);
    ~itkDataSHImageReaderPlugin(void);

    virtual bool initialize(void);
    virtual bool uninitialize(void);

    virtual QString name(void) const;
    virtual QString description(void) const;

    virtual QStringList tags(void) const;
    virtual QStringList types(void) const;

private:
     itkDataSHImageReaderPluginPrivate *d;
};

#endif
