// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#ifndef EXAMPLEPROCESSIMAGEFILTERPLUGINEXPORT_H
#define EXAMPLEPROCESSIMAGEFILTERPLUGINEXPORT_H

#ifdef WIN32
    #ifdef exampleProcessImageFilterPlugin_EXPORTS
        #define EXAMPLEPROCESSIMAGEFILTERPLUGIN_EXPORT __declspec(dllexport) 
    #else
        #define EXAMPLEPROCESSIMAGEFILTERPLUGIN_EXPORT __declspec(dllimport) 
    #endif
#else
    #define EXAMPLEPROCESSIMAGEFILTERPLUGIN_EXPORT
#endif

#endif
