// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////



#ifndef EXAMPLEPROCESSIMAGEFILTERPLUGIN_H
#define EXAMPLEPROCESSIMAGEFILTERPLUGIN_H

#include <dtkCore/dtkPlugin.h>

#include "exampleProcessImageFilterPluginExport.h"

class EXAMPLEPROCESSIMAGEFILTERPLUGIN_EXPORT exampleProcessImageFilterPluginPrivate;

/**
* @class exampleProcessImageFilterPlugin
* @brief A simple example process plugin, the input are 2 UNSIGNED SHORT 3D images that can be added, masked. Region growing can also be applyed to the first image.
* It gets two 3D unsigned short images trough the medDiffusionAbstractToolBox and exampleProcessImageFilterToolBox.h drop sites,
* three operations can be done to thos images:
* 1 MASK the first image with the second one
* 2 ADD the two images
* 3 APPLY CONNECTED THRESHOLD to the first image, the three first spin boxes, specify the seed voxel, the fourth specifies
* the lower intensity threshold used, the upper one is +150 teh lower
**/

class EXAMPLEPROCESSIMAGEFILTERPLUGIN_EXPORT exampleProcessImageFilterPlugin : public dtkPlugin
{
    Q_OBJECT
    Q_INTERFACES(dtkPlugin)

public:
     exampleProcessImageFilterPlugin(QObject *parent = 0);
    ~exampleProcessImageFilterPlugin(void);

    /**
    * Initializes the exampleProcessImageFilterPlugin by registering the exampleProcessImageFilter type and the
    * exampleProcessImageFilter toolbox
    **/
    virtual bool initialize(void);
    virtual bool uninitialize(void);

    virtual QString name(void) const;
    virtual QString description(void) const;

    virtual QStringList tags(void) const;
    virtual QStringList types(void) const;

private:
     exampleProcessImageFilterPluginPrivate *d;
};

#endif
