// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#ifndef ITKDATAREADERPLUGIN_H
#define ITKDATAREADERPLUGIN_H

#include <dtkCore/dtkPlugin.h>

#include "itkDataReaderPluginExport.h"

class ITKDATAREADERPLUGIN_EXPORT itkDataReaderPluginPrivate;

class ITKDATAREADERPLUGIN_EXPORT itkDataReaderPlugin : public dtkPlugin
{
    Q_OBJECT
    Q_INTERFACES(dtkPlugin)

public:
     itkDataReaderPlugin(QObject *parent = 0);
    ~itkDataReaderPlugin(void);

    virtual bool initialize(void);
    virtual bool uninitialize(void);

    virtual QString name(void) const;
    virtual QString description(void) const;

    virtual QStringList tags(void) const;
    virtual QStringList types(void) const;

private:
     itkDataReaderPluginPrivate *d;
};

#endif
