// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#ifndef ITKPROCESSTENSORLOGEUCLIDEANPLUGINEXPORT_H
#define ITKPROCESSTENSORLOGEUCLIDEANPLUGINEXPORT_H

#ifdef WIN32
    #ifdef itkProcessTensorLogEuclideanPlugin_EXPORTS
        #define ITKPROCESSTENSORLOGEUCLIDEANPLUGIN_EXPORT __declspec(dllexport) 
    #else
        #define ITKPROCESSTENSORLOGEUCLIDEANPLUGIN_EXPORT __declspec(dllimport) 
    #endif
#else
    #define ITKPROCESSTENSORLOGEUCLIDEANPLUGIN_EXPORT __attribute__ ((visibility ("default")))
#endif

#endif
