// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#ifndef UNDOREDOREGISTRATIONPLUGINEXPORT_H
#define UNDOREDOREGISTRATIONPLUGINEXPORT_H

#ifdef WIN32
    #ifdef undoRedoRegistrationPlugin_EXPORTS
        #define UNDOREDOREGISTRATIONPLUGIN_EXPORT __declspec(dllexport) 
    #else
        #define UNDOREDOREGISTRATIONPLUGIN_EXPORT __declspec(dllimport) 
    #endif
#else
    #define UNDOREDOREGISTRATIONPLUGIN_EXPORT
#endif

#endif
