if (UNIX)
    if (APPLE)
        set(platform_suffix mac)
    else()
        set(platform_suffix linux)
    endif()
elseif (WIN32)
    set(platform_suffix win)
endif()

set(download_url "https://med.inria.fr/downloads/embedded-python/python-3.${PYTHON_VERSION_MINOR}-${platform_suffix}.zip")
message("Downloading the embeddable Python package from ${download_url}")
file(DOWNLOAD ${download_url} "${PYTHON_ZIP}" STATUS download_status)
list(POP_FRONT download_status download_code download_error)

if (download_code)
    message(WARNING "Downloading of Python package failed: ${download_error} (${download_code})")
else()
    message("Download of Python package succeeded: ${PYTHON_ZIP}")
endif()
