// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#ifndef VTKDATAFIBERSPLUGIN_H
#define VTKDATAFIBERSPLUGIN_H

#include <dtkCore/dtkPlugin.h>

#include "vtkDataFibersPluginExport.h"

class VTKDATAFIBERSPLUGIN_EXPORT vtkDataFibersPluginPrivate;

class VTKDATAFIBERSPLUGIN_EXPORT vtkDataFibersPlugin : public dtkPlugin
{
    Q_OBJECT
    Q_INTERFACES(dtkPlugin)

public:
     vtkDataFibersPlugin(QObject *parent = 0);
    ~vtkDataFibersPlugin(void);

    virtual bool initialize(void);
    virtual bool uninitialize(void);

    virtual QString name(void) const;
    virtual QString description(void) const;

    virtual QStringList tags(void) const;
    virtual QStringList types(void) const;

private:
     vtkDataFibersPluginPrivate *d;
};

#endif
