// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#include "itkDataSHImageDouble3.h"

#include <dtkCore/dtkAbstractDataFactory.h>

#include <itkImage.h>
#include <itkImageRegionConstIterator.h>
#include <itkImageRegionIteratorWithIndex.h>
#include <itkImageFileWriter.h>
#include <itkVectorImage.h>
#include <itkVector.h>

// /////////////////////////////////////////////////////////////////
// itkDataSHImagePrivate
// /////////////////////////////////////////////////////////////////

class itkDataSHImageDouble3Private
{
public:
    typedef itk::VectorImage<double, 3> SHImageType;
    typedef SHImageType::PixelType    SHType;

    SHImageType::Pointer shs;

    QImage        thumbnail;
    QList<QImage> thumbnails;
};

// /////////////////////////////////////////////////////////////////
// itkDataSHImage
// /////////////////////////////////////////////////////////////////

itkDataSHImageDouble3::itkDataSHImageDouble3(void) : medAbstractDataTypedImage<3,double>(), d(new itkDataSHImageDouble3Private)
{
    d->shs = 0;
    d->thumbnail = QImage(":/itkDataSHImage/icons/shs.png");
    d->thumbnails << d->thumbnail;
}

itkDataSHImageDouble3::~itkDataSHImageDouble3(void)
{
    delete d;
    d = 0;
}

bool itkDataSHImageDouble3::registered(void)
{
    return dtkAbstractDataFactory::instance()->registerDataType("itkDataSHImageDouble3", createItkDataSHImageDouble3);
}

QString itkDataSHImageDouble3::description(void) const
{
    return tr("itk spherical harmonic 3d image data (double)");
}
QString itkDataSHImageDouble3::identifier(void) const
{
    return "itkDataSHImageDouble3";
}

void *itkDataSHImageDouble3::data(void)
{
    std::cerr << "Image: " << xDimension() << 'x' << yDimension() << 'x' << zDimension() << std::endl;
    return d->shs.GetPointer();
}

void *itkDataSHImageDouble3::output(void)
{
    return d->shs.GetPointer();
}

void itkDataSHImageDouble3::setData(void *data)
{
    typedef itkDataSHImageDouble3Private::SHImageType SHImageType;

    if( SHImageType* shs = dynamic_cast<SHImageType*>( (itk::Object*)(data) ) ){
        d->shs = shs;
    }
    else
      qDebug() << "Cannot cast pointer to correct SH double type";
}

int itkDataSHImageDouble3::xDimension (void)
{
    if (!d->shs.IsNull())
      return d->shs->GetLargestPossibleRegion().GetSize()[0];
    return -1;
}

int itkDataSHImageDouble3::yDimension (void)
{
    if (!d->shs.IsNull())
        return d->shs->GetLargestPossibleRegion().GetSize()[1];
    return -1;
}

int itkDataSHImageDouble3::zDimension (void)
{
    if (!d->shs.IsNull())
        return d->shs->GetLargestPossibleRegion().GetSize()[2];
    return -1;
}

QImage& itkDataSHImageDouble3::thumbnail  (void) const
{
    // TODO: TEMPORARY black image just to allow drag and drop
    return d->thumbnail;
}

QList<QImage>& itkDataSHImageDouble3::thumbnails (void) const
{
    return d->thumbnails;
}

// /////////////////////////////////////////////////////////////////
// Type instantiation
// /////////////////////////////////////////////////////////////////

dtkAbstractData *createItkDataSHImageDouble3(void)
{
    return new itkDataSHImageDouble3;
}
