// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#include "itkDataImage.h"
#include "itkDataPlugin.h"

#include <dtkCore/dtkLog.h>

// /////////////////////////////////////////////////////////////////
// itkDataPluginPrivate
// /////////////////////////////////////////////////////////////////

class itkDataPluginPrivate 
{
public:
    // Class variables go here.
};

// /////////////////////////////////////////////////////////////////
// itkDataPlugin
// /////////////////////////////////////////////////////////////////

itkDataPlugin::itkDataPlugin(QObject *parent) : dtkPlugin(parent), d(new itkDataPluginPrivate)
{

}

itkDataPlugin::~itkDataPlugin(void)
{
    delete d;

    d = NULL;
}

bool itkDataPlugin::initialize(void)
{
  if(!itkDataImageChar3::registered()) qDebug() << "Unable to register itkDataImageChar3 type";
  if(!itkDataImageUChar3::registered()) qDebug() << "Unable to register itkDataImageUChar3 type";
  if(!itkDataImageShort3::registered()) qDebug() << "Unable to register itkDataImageShort3 type";
  if(!itkDataImageUShort3::registered()) qDebug() << "Unable to register itkDataImageUShort3 type";
  if(!itkDataImageInt3::registered()) qDebug() << "Unable to register itkDataImageInt3 type";
  if(!itkDataImageUInt3::registered()) qDebug() << "Unable to register itkDataImageUInt3 type";
  if(!itkDataImageLong3::registered()) qDebug() << "Unable to register itkDataImageLong3 type";
  if(!itkDataImageULong3::registered()) qDebug() << "Unable to register itkDataImageULong3 type";
  if(!itkDataImageFloat3::registered()) qDebug() << "Unable to register itkDataImageFloat3 type";
  if(!itkDataImageDouble3::registered()) qDebug() << "Unable to register itkDataImageDouble3 type";
  
  return true;
}

bool itkDataPlugin::uninitialize(void)
{
    return true;
}

QString itkDataPlugin::name(void) const
{
    return "itkDataPlugin";
}

QString itkDataPlugin::description(void) const
{
    return "Plugin containing all types of ITK images";
}

QStringList itkDataPlugin::tags(void) const
{
  return QStringList() << "itk" << "data" << "image";
}

QStringList itkDataPlugin::types(void) const
{
  return QStringList() << "itkDataImageChar3"
		       << "itkDataImageUChar3"
		       << "itkDataImageShort3"
		       << "itkDataImageUShort3"
		       << "itkDataImageInt3"
		       << "itkDataImageUInt3"
		       << "itkDataImageLong3"
		       << "itkDataImageULong3"
		       << "itkDataImageFloat3"
		       << "itkDataImageDouble3";
}

Q_EXPORT_PLUGIN2(itkDataPlugin, itkDataPlugin)
