// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#ifndef ITKDATAPLUGINEXPORT_H
#define ITKDATAPLUGINEXPORT_H

#ifdef WIN32
    #ifdef itkDataPlugin_EXPORTS
        #define ITKDATAPLUGIN_EXPORT __declspec(dllexport) 
    #else
        #define ITKDATAPLUGIN_EXPORT __declspec(dllimport) 
    #endif
#else
    #define ITKDATAPLUGIN_EXPORT
#endif

#endif

