// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#ifndef ITKDATAIMAGEBASEEXPORT_H
#define ITKDATAIMAGEBASEEXPORT_H

#ifdef WIN32
    #ifdef itkDataImageBase_EXPORTS
        #define ITKDATAIMAGEBASE_EXPORT __declspec(dllexport)
    #else
        #define ITKDATAIMAGEBASE_EXPORT __declspec(dllimport)
    #endif
#else
    #define ITKDATAIMAGEBASE_EXPORT
#endif

#endif

