// /////////////////////////////////////////////////////////////////
// Generated by medPluginGenerator
// /////////////////////////////////////////////////////////////////

#include "DiffusionSequenceCompositeData.h"

#include <dtkCore/dtkAbstractDataFactory.h>

// /////////////////////////////////////////////////////////////////
// DiffusionSequenceCompositeDataPrivate
// /////////////////////////////////////////////////////////////////

class DiffusionSequenceCompositeDataPrivate
{
public:
};

// /////////////////////////////////////////////////////////////////
// DiffusionSequenceCompositeData
// /////////////////////////////////////////////////////////////////

DiffusionSequenceCompositeData::DiffusionSequenceCompositeData(void) : dtkAbstractData(), d(new DiffusionSequenceCompositeDataPrivate)
{

}

DiffusionSequenceCompositeData::~DiffusionSequenceCompositeData(void)
{

}

bool DiffusionSequenceCompositeData::registered(void)
{
    return dtkAbstractDataFactory::instance()->registerDataType("DiffusionSequenceCompositeData", createMedCompositeDataSets);
}

QString DiffusionSequenceCompositeData::description(void) const
{
    return "DiffusionSequenceCompositeData";
}

// /////////////////////////////////////////////////////////////////
// Type instantiation
// /////////////////////////////////////////////////////////////////

dtkAbstractData *createMedCompositeDataSets(void)
{
    return new DiffusionSequenceCompositeData;
}
