// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#ifndef MEDCOMPOSITEDATASETSPLUGINEXPORT_H
#define MEDCOMPOSITEDATASETSPLUGINEXPORT_H

#ifdef WIN32
    #ifdef medCompositeDataSetsPlugin_EXPORTS
        #define MEDCOMPOSITEDATASETSPLUGIN_EXPORT __declspec(dllexport) 
    #else
        #define MEDCOMPOSITEDATASETSPLUGIN_EXPORT __declspec(dllimport) 
    #endif
#else
    #define MEDCOMPOSITEDATASETSPLUGIN_EXPORT
#endif

#endif
