// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#ifndef ITKFILTERSPLUGINEXPORT_H
#define ITKFILTERSPLUGINEXPORT_H

#ifdef WIN32
    #ifdef itkFiltersPlugin_EXPORTS
        #define ITKFILTERSPLUGIN_EXPORT __declspec(dllexport)
    #else
        #define ITKFILTERSPLUGIN_EXPORT __declspec(dllimport)
    #endif
#else
    #define ITKFILTERSPLUGIN_EXPORT
#endif

#endif
