#!/bin/sh
# postinst script

set -e
# TODO: configure this file with CMake and change the hardcoded install path
# the medinria.desktop file is installed by the medinria project
# here we copy it to the proper directory so it is found by Ubuntu
ln -s /usr/local/inria/share/applications/medinria.desktop /usr/share/applications/medinria.desktop

