#!/bin/sh
# prerm script

# TODO: configure this file with CMake and change the hardcoded install path
sudo rm -f /usr/local/inria/lib/libquazip.so
sudo rm -f /usr/share/applications/medinria.desktop
