#!/bin/sh
# prerm script

# TODO: configure this file with CMake and change the hardcoded install path
# test if the files are symbolic links first: important especially for the executable, in case the user has medinria1 in its /usr/bin path
[ -h /usr/share/applications/medinria.desktop ] && rm -f /usr/share/applications/medinria.desktop

[ -h /usr/bin/medinria ]  && rm -f /usr/bin/medinria
