// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#ifndef ITKADDCONSTANTTOIMAGEFILTER_H
#define ITKADDCONSTANTTOIMAGEFILTER_H

#include <dtkCore/dtkAbstractProcess.h>
#include <dtkCore/dtkAbstractData.h>

#include "itkAddConstantToImageFilterPluginExport.h"

class itkAddConstantToImagePrivate;
class dtkAbstractData;

class ITKADDCONSTANTTOIMAGEFILTERPLUGIN_EXPORT itkAddConstantToImage : public dtkAbstractProcess
{
    Q_OBJECT

public:
             itkAddConstantToImage(void);
    virtual ~itkAddConstantToImage(void);

    virtual QString description(void) const;

    static bool registered(void);

public slots:

    void setInput(dtkAbstractData *data);
    void setParameter(double  data, int channel);
    int update(void);
    dtkAbstractData *output(void);

private:
    itkAddConstantToImagePrivate *d;
};

dtkAbstractProcess *createitkAddConstantToImage(void);

#endif
