// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#ifndef ITKPROCESSREGISTRATIONSUPERBALOOPLUGINEXPORT_H
#define ITKPROCESSREGISTRATIONSUPERBALOOPLUGINEXPORT_H

#ifdef WIN32
    #ifdef itkProcessRegistrationSuperBalooPlugin_EXPORTS
        #define ITKPROCESSREGISTRATIONSUPERBALOOPLUGIN_EXPORT __declspec(dllexport)
    #else
        #define ITKPROCESSREGISTRATIONSUPERBALOOPLUGIN_EXPORT __declspec(dllimport)
    #endif
#else
    #define ITKPROCESSREGISTRATIONSUPERBALOOPLUGIN_EXPORT __attribute__ ((visibility ("default")))
#endif

#endif
