#!/bin/bash

#PIPOL linux-fedora 3:00 --root
#PIPOL linux-ubuntu 3:00 --root
#PIPOL windows-xp 4:00 --root


cd $PIPOL_HOMEDIR/scripts

DATE=`date +%Y-%m-%d`
mkdir -p $PIPOL_HOMEDIR/log/

case $PIPOL_IMAGE in
	*-windows-xp-*)
    ./installer.py -f run_pipol_winxp.cfg &> $PIPOL_HOMEDIR/log/$DATE-$PIPOL_IMAGE-$PIPOL_JOB_ID
	
	;;
	*-linux-fedora-*)
	./installer.py -f run_linux.cfg -f run_pipol_fed.cfg --no-package-deps 
	
	;;
	*-linux-ubuntu-*)
	./installer.py -f run_linux.cfg -f run_pipol_ubuntu.cfg --no-package-deps
	;;
	
	*-linux-debian-*)
	./installer.py -f run_linux.cfg -f run_pipol_fed.cfg --no-package-deps
	;;
	
	*)
	;;
esac


#    amd64_kvm-linux-debian-lenny
#    amd64_kvm-linux-debian-testing
#    amd64_kvm-windows-7
#    amd64-linux-centos-5.dd.gz
#    amd64-linux-debian-etch.dd.gz
#    amd64-linux-debian-lenny.dd.gz
#    amd64-linux-debian-testing.dd.gz
#    amd64-linux-fedora-core10.dd.gz
#    amd64-linux-fedora-core11.dd.gz
#    amd64-linux-fedora-core12.dd.gz
#    amd64-linux-fedora-core13.dd.gz
#    amd64-linux-fedora-core7.dd.gz
#    amd64-linux-fedora-core8.dd.gz
#    amd64-linux-fedora-core9.dd.gz
#    amd64-linux-mandriva-2007_springs_powerpack.dd.gz
#    amd64-linux-mandriva-2009_powerpack.dd.gz
#    amd64-linux-opensuse-11.dd.gz
#    amd64-linux-redhatEL-5.0.dd.gz
#    amd64-linux-suse-LES10.dd.gz
#    amd64-linux-ubuntu-feisty.dd.gz
#    amd64-linux-ubuntu-hardy.dd.gz
#    amd64-linux-ubuntu-intrepid.dd.gz
#    amd64-linux-ubuntu-jaunty.dd.gz
#    amd64-linux-ubuntu-karmic.dd.gz
#    amd64-linux-ubuntu-lucid.dd.gz
#    amd64-unix-freebsd-7.dd.gz
#    amd64-windows-server-2003-64bits.dd.gz
#    amd64-windows-server-2008-64bits.dd.gz
#    i386_kvm-linux-debian-lenny
#    i386_kvm-linux-debian-testing
#    i386_kvm-linux-fedora-core13
#    i386_kvm-windows-xp-pro-sp3
#    i386-linux-centos-5.dd.gz
#    i386-linux-debian-etch.dd.gz
#    i386-linux-debian-lenny.dd.gz
#    i386-linux-debian-testing.dd.gz
#    i386-linux-fedora-core10.dd.gz
#    i386-linux-fedora-core11.dd.gz
#    i386-linux-fedora-core12.dd.gz
#    i386-linux-fedora-core13.dd.gz
#    i386-linux-fedora-core7.dd.gz
#    i386-linux-fedora-core8.dd.gz
#    i386-linux-fedora-core9.dd.gz
#    i386-linux-mandriva-2007_springs_powerpack.dd.gz
#    i386-linux-mandriva-2009_powerpack.dd.gz
#    i386-linux-opensuse-11.dd.gz
#    i386-linux-redhatEL-5.0.dd.gz
#    i386-linux-suse-LES10.dd.gz
#    i386-linux-ubuntu-feisty.dd.gz
#    i386-linux-ubuntu-hardy.dd.gz
#    i386-linux-ubuntu-intrepid.dd.gz
#    i386-linux-ubuntu-jaunty.dd.gz
#    i386-linux-ubuntu-karmic.dd.gz
#    i386-linux-ubuntu-lucid.dd.gz
#    i386_mac-mac-osx-server-leopard.dd.gz
#    i386-unix-freebsd-7.dd.gz
#    i386-unix-opensolaris-10.dd.gz
#    i386-unix-opensolaris-11.dd.gz
#    i386-unix-solaris-10.dd.gz
#    ia64-linux-debian-lenny.dd
#    ia64-linux-fedora-core9.dd
#    ia64-linux-redhatEL-5.0.dd
#    x86_64_mac-mac-osx-server-snow-leopard.dd.gz
#    x86_mac-mac-osx-server-snow-leopard.dd.gz
