// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#pragma once

#ifdef WIN32
    #ifdef v3dDataPlugin_EXPORTS
        #define V3DDATAPLUGIN_EXPORT __declspec(dllexport) 
    #else
        #define V3DDATAPLUGIN_EXPORT __declspec(dllimport) 
    #endif
#else
    #define V3DDATAPLUGIN_EXPORT
#endif



