// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#pragma once

#ifdef WIN32
    #ifdef itkDataTensorImageReaderPlugin_EXPORTS
        #define ITKDATATENSORIMAGEREADERPLUGIN_EXPORT __declspec(dllexport) 
    #else
        #define ITKDATATENSORIMAGEREADERPLUGIN_EXPORT __declspec(dllimport) 
    #endif
#else
    #define ITKDATATENSORIMAGEREADERPLUGIN_EXPORT
#endif


