// /////////////////////////////////////////////////////////////////
// Generated by dtkPluginGenerator
// /////////////////////////////////////////////////////////////////

#pragma once

#ifdef WIN32
    #ifdef itkProcessRegistration_EXPORTS
        #define ITKPROCESSREGISTRATION_EXPORT __declspec(dllexport) 
    #else
        #define ITKPROCESSREGISTRATION_EXPORT __declspec(dllimport) 
    #endif
#else
    #define ITKPROCESSREGISTRATION_EXPORT
#endif


