# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: medInria on macOS

on:
  push:
    branches: [ "medInria6.0.x" ]

  # Parameters displayed for users for manual runs in Github Action GUI
  workflow_dispatch:
    inputs:
      BRANCH:
        description: 'Branch to checkout'
        required: true
        default: 'medInria6.0.x'
        type: string
      RELEASE:
        description: 'Github release tag to send to'
        required: true
        default: 'V6.0.0'
        type: string

  # Reusable workflow from other scripts (weekly, monthly, etc)
  workflow_call:
    inputs:
      BRANCH:
        required: true
        type: string
        default: 'medInria6.0.x'
      RELEASE:
        required: true
        type: string
        default: 'V6.0.0'

env:
  BUILD_TYPE: Release
  QT5_DIR: "/opt/homebrew/opt/qt@5/lib/cmake/Qt5" # Apple chip
  #QT5_DIR: "/usr/local/opt/qt@5/lib/cmake/Qt5" # Intel chip
  # Secrets added on https://github.com/medInria/medInria-public/settings/secrets/actions/new and on your fork for testing purpose
  BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
  P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
  CERT_NAME: "MDS-certificate"

jobs:
  build:
    # https://docs.github.com/en/actions/using-jobs/choosing-the-runner-for-a-job#standard-github-hosted-runners-for-public-repositories
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v7
      with:
          ref: ${{ inputs.BRANCH }}

    - name: Save in environment variable in case of automatic runs
      run: |
        echo "RELEASE=${{ inputs.RELEASE || 'V6.0.0' }}" >> $GITHUB_ENV

    # Dependencies, already on the runner: pipx, cmake
    - name: Install dependencies
      run: |
        brew install qt@5
        echo 'export PATH="/opt/homebrew/opt/qt@5/bin:$PATH"' >> /Users/runner/.bash_profile # Apple chip
        #echo 'export PATH="/usr/local/opt/qt@5/bin:$PATH"' >> /Users/runner/.bash_profile # Intel chip
        brew link --force qt@5
        brew install boost
        brew install libomp
        echo "OpenMP_ROOT=$(brew --prefix libomp)" >> $GITHUB_ENV
        pipx install dmgbuild
        pipx ensurepath

    - name: Test dependencies
      run: |
        pipx --version
        which dmgbuild
        cmake --version
        ls $QT5_DIR

    ### Steps for macOS signing with self-signed certificate ###
    #
    # 1. Create a p12 certificate on a physical macOS:
    #    - Open /Applications/Utilities/Keychain Access.app or in /System/Library/CoreServices/Applications on newer macOS.
    #    - Menu Keychain Access -> Certificate Assistant -> Create a Certificate...
    #         - Name: MDS-certificate.
    #         - Identity Type: Self‑Signed Root.
    #         - Certificate Type: Code Signing.
    #    - Switch the certificate to "Always Trust":
    #         - Select the certificate in "login" and "Certificates".
    #         - Double-click on it.
    #         - In "Trust" section, choose "Always Trust" for "When using this certificate".
    #         - Close the window and validate with admin password.
    #         - If needed: restart computer.
    # 2. Export the certificate as p12:
    #    - In Keychain Access find the certificate line.
    #    - Left click to display the private key.
    #    - Right click on the private key -> Exporter "MDS-certificate".
    #    - Choose a name (MDS-certificate) and the format (Personal Information Exchange .p12).
    #    - Define a strong password and save MDS-certificate.p12.
    #    - If necessary, keep them in a safe place.
    # 3. Import certificate in CI/CD:
    #    - On the physical macOS, copy the p12 certificate with: 'base64 -i MDS-certificate.p12 | pbcopy'.
    #    - On https://github.com/medInria/medInria-public/settings/secrets/actions/new.
    #        - add BUILD_CERTIFICATE_BASE64 with the previously encoded lines.
    #        - add P12_PASSWORD with p12 password.
    #    - For test purposes you need to add the secrets also on your forks.
    ###

    # https://github.com/marketplace/actions/import-code-signing-certificates
    - name: Install our self-signed certificate
      id: import-certs
      uses: apple-actions/import-codesign-certs@v7
      with: 
        p12-file-base64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
        p12-password:    ${{ secrets.P12_PASSWORD }}

    - name: Add the certificate to trusted list for code signing
      shell: bash
      run: |
        # Extract the PEM certificate from the p12
        echo "$BUILD_CERTIFICATE_BASE64" | base64 --decode > /tmp/cert.p12
        openssl pkcs12 -legacy -in /tmp/cert.p12 -passin pass:"$P12_PASSWORD" \
          -clcerts -nokeys -out /tmp/cert.pem

        # Display a failure when the certificate is about to expire
        openssl x509 -in /tmp/cert.pem -checkend 604800 -noout || {
          echo "ERROR: certificate '$CERT_NAME' expires in less than 7 days"
          echo "Current expiry date: $(openssl x509 -in /tmp/cert.pem -enddate -noout | cut -d= -f2)"
          exit 1
        }

        # Add trusted certificate to system keychain
        sudo security add-trusted-cert -d -r trustRoot -p codeSign \
          -k /Library/Keychains/System.keychain /tmp/cert.pem

    - name: Verify certificate
      shell: bash
      run: |
        security find-identity -v -p codesigning | grep -F -q "$CERT_NAME" || {
          echo "Error, certificate '$CERT_NAME' not found in valid identities"
          security find-identity -v -p codesigning
          exit 1
        }

    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build \
          -DUSE_GITHUB_SSH:BOOL=FALSE \
          -DmedInria_BUILD_TYPE:STRING=${{env.BUILD_TYPE}} \
          -DEP_CHECKBOX_CUSTOM_DIRS:BOOL=ON \
          -DEP_CHECKBOX_ON_TOP_LEVEL:BOOL=OFF \
          -DEP_CHECKBOX_SIDE_BY_SIDE:BOOL=OFF \
          -DQt5_DIR=$QT5_DIR \
          -DOpenMP_ROOT=$OpenMP_ROOT

    - name: Build
      run: |
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --parallel 4

    - name: Package
      run: |
        cd ${{github.workspace}}/build
        cpack -C ${{env.BUILD_TYPE}}

    - name: Get binary name
      run: |
        cd ${{github.workspace}}/build
        binary=$(ls *.dmg | head -n 1)
        echo "BINARY_NAME=$binary" >> $GITHUB_ENV
        echo "The current package: $binary"
    
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        file: ${{github.workspace}}/build/${{env.BINARY_NAME}}
        asset_name: ${{env.BINARY_NAME}}
        tag: ${{env.RELEASE}}
        overwrite: true
